<?xml version="1.0" encoding="utf-8"?><Database Name="CellLoadSharing" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="MRR小区小时常规统计">
    <Type Name="MRR小区小时常规统计">
      <Column Name="时间" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="小区名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="DL覆盖94" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DL覆盖90" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DL覆盖85" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DL覆盖75" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DL覆盖采样数" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="现网cdd">
    <Type Name="现网cdd">
      <Column Name="cellid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cell_name" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="accmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cchpwr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[to]" Member="to" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CELL" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="BSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="NW" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="MSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="现网cdd_Nrel">
    <Type Name="现网cdd_Nrel">
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NW" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="MSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="BSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="CELL" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="cellid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cell_name" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="n_cell" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="n_cellid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="n_cell_name" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="n_bsc" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="awoffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bqoffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bqoffsetafr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cand" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="cs" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="gprsvalid" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="hihyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="khyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="koffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lhyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lohyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="offset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="proffset" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="trhyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="troffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="小区基础数据">
    <Type Name="小区基础数据">
      <Column Name="小区名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="小区号" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="状态" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="基站名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="BSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="LAI" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="CI" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="经度" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="纬度" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="详细地址" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="方向角" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="下倾角" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="相对高度" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="海拔高度" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="功分编号" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="天线数目" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="小区切换查询">
    <Type Name="小区切换查询">
      <Column Name="切换次数" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="小区名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="邻小区名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="CELLGPRS">
    <Type Name="CELLGPRS">
      <Column Name="时间" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="小区名" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="小区号" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="BSC" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="下行TBF建立成功率" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EDGE每线下行激活用户" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GPRS每线下行激活用户" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="平均分配PDCH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GPRS下行激活信道" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EDGE下行激活信道" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EDGE每线下行用户" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EDGE终端使用EDGE比例" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GPRS每线下行用户" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="T可用信道" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T话务量" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="H话务比" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FAILDLTBFEST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDCH复用度" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>