#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellLoadSharing
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CellLoadSharing")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CellLoadSharing.Properties.Settings.Default.CellLoadSharingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CELLGPRS_0822_1> CELLGPRS_0822_1
		{
			get
			{
				return this.GetTable<CELLGPRS_0822_1>();
			}
		}
		
		public System.Data.Linq.Table<MRR_0822> MRR_0822
		{
			get
			{
				return this.GetTable<MRR_0822>();
			}
		}
		
		public System.Data.Linq.Table<现网cdd_0822> 现网cdd_0822
		{
			get
			{
				return this.GetTable<现网cdd_0822>();
			}
		}
		
		public System.Data.Linq.Table<现网cdd_Nrel_0822> 现网cdd_Nrel_0822
		{
			get
			{
				return this.GetTable<现网cdd_Nrel_0822>();
			}
		}
		
		public System.Data.Linq.Table<小区基础数据_0822> 小区基础数据_0822
		{
			get
			{
				return this.GetTable<小区基础数据_0822>();
			}
		}
		
		public System.Data.Linq.Table<小区切换查询_0822_1> 小区切换查询_0822_1
		{
			get
			{
				return this.GetTable<小区切换查询_0822_1>();
			}
		}
		
		public System.Data.Linq.Table<CELLGPRS_0902_1> CELLGPRS_0902_1
		{
			get
			{
				return this.GetTable<CELLGPRS_0902_1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CELLGPRS_0822_1")]
	public partial class CELLGPRS_0822_1
	{
		
		private System.Nullable<System.DateTime> _时间;
		
		private string _小区名;
		
		private string _小区号;
		
		private string _BSC;
		
		private System.Nullable<double> _下行TBF建立成功率;
		
		private System.Nullable<double> _平均分配PDCH;
		
		private System.Nullable<double> _EDGE下行激活信道;
		
		private System.Nullable<double> _EDGE每线下行用户;
		
		private System.Nullable<double> _EDGE终端使用EDGE比例;
		
		private System.Nullable<double> _PDCH复用度;
		
		private System.Nullable<double> _GPRS下行激活信道;
		
		private System.Nullable<double> _GPRS每线下行用户;
		
		private System.Nullable<int> _T可用信道;
		
		private System.Nullable<double> _T话务量;
		
		private System.Nullable<double> _H话务比;
		
		private System.Nullable<int> _FAILDLTBFEST;
		
		public CELLGPRS_0822_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时间", DbType="DateTime")]
		public System.Nullable<System.DateTime> 时间
		{
			get
			{
				return this._时间;
			}
			set
			{
				if ((this._时间 != value))
				{
					this._时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区名", DbType="NVarChar(254)")]
		public string 小区名
		{
			get
			{
				return this._小区名;
			}
			set
			{
				if ((this._小区名 != value))
				{
					this._小区名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区号", DbType="NVarChar(254)")]
		public string 小区号
		{
			get
			{
				return this._小区号;
			}
			set
			{
				if ((this._小区号 != value))
				{
					this._小区号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_下行TBF建立成功率", DbType="Float")]
		public System.Nullable<double> 下行TBF建立成功率
		{
			get
			{
				return this._下行TBF建立成功率;
			}
			set
			{
				if ((this._下行TBF建立成功率 != value))
				{
					this._下行TBF建立成功率 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_平均分配PDCH", DbType="Float")]
		public System.Nullable<double> 平均分配PDCH
		{
			get
			{
				return this._平均分配PDCH;
			}
			set
			{
				if ((this._平均分配PDCH != value))
				{
					this._平均分配PDCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE下行激活信道", DbType="Float")]
		public System.Nullable<double> EDGE下行激活信道
		{
			get
			{
				return this._EDGE下行激活信道;
			}
			set
			{
				if ((this._EDGE下行激活信道 != value))
				{
					this._EDGE下行激活信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE每线下行用户", DbType="Float")]
		public System.Nullable<double> EDGE每线下行用户
		{
			get
			{
				return this._EDGE每线下行用户;
			}
			set
			{
				if ((this._EDGE每线下行用户 != value))
				{
					this._EDGE每线下行用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE终端使用EDGE比例", DbType="Float")]
		public System.Nullable<double> EDGE终端使用EDGE比例
		{
			get
			{
				return this._EDGE终端使用EDGE比例;
			}
			set
			{
				if ((this._EDGE终端使用EDGE比例 != value))
				{
					this._EDGE终端使用EDGE比例 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDCH复用度", DbType="Float")]
		public System.Nullable<double> PDCH复用度
		{
			get
			{
				return this._PDCH复用度;
			}
			set
			{
				if ((this._PDCH复用度 != value))
				{
					this._PDCH复用度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPRS下行激活信道", DbType="Float")]
		public System.Nullable<double> GPRS下行激活信道
		{
			get
			{
				return this._GPRS下行激活信道;
			}
			set
			{
				if ((this._GPRS下行激活信道 != value))
				{
					this._GPRS下行激活信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPRS每线下行用户", DbType="Float")]
		public System.Nullable<double> GPRS每线下行用户
		{
			get
			{
				return this._GPRS每线下行用户;
			}
			set
			{
				if ((this._GPRS每线下行用户 != value))
				{
					this._GPRS每线下行用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T可用信道", DbType="Int")]
		public System.Nullable<int> T可用信道
		{
			get
			{
				return this._T可用信道;
			}
			set
			{
				if ((this._T可用信道 != value))
				{
					this._T可用信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T话务量", DbType="Float")]
		public System.Nullable<double> T话务量
		{
			get
			{
				return this._T话务量;
			}
			set
			{
				if ((this._T话务量 != value))
				{
					this._T话务量 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H话务比", DbType="Float")]
		public System.Nullable<double> H话务比
		{
			get
			{
				return this._H话务比;
			}
			set
			{
				if ((this._H话务比 != value))
				{
					this._H话务比 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAILDLTBFEST", DbType="Int")]
		public System.Nullable<int> FAILDLTBFEST
		{
			get
			{
				return this._FAILDLTBFEST;
			}
			set
			{
				if ((this._FAILDLTBFEST != value))
				{
					this._FAILDLTBFEST = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MRR_0822")]
	public partial class MRR_0822
	{
		
		private System.Nullable<System.DateTime> _时间;
		
		private string _小区名;
		
		private System.Nullable<double> _DL覆盖94;
		
		private System.Nullable<double> _DL覆盖90;
		
		private System.Nullable<double> _DL覆盖85;
		
		private System.Nullable<double> _DL覆盖75;
		
		private System.Nullable<int> _DL覆盖采样数;
		
		private System.Nullable<double> _DL覆盖0;
		
		private System.Nullable<double> _DL覆盖1;
		
		private System.Nullable<double> _DL覆盖2;
		
		private System.Nullable<double> _DL覆盖3;
		
		private System.Nullable<double> _DL覆盖4;
		
		private System.Nullable<double> _DL覆盖5;
		
		private System.Nullable<double> _DL覆盖6;
		
		private System.Nullable<double> _DL覆盖7;
		
		private System.Nullable<double> _DL覆盖8;
		
		private System.Nullable<double> _DL覆盖9;
		
		private System.Nullable<double> _DL覆盖10;
		
		private System.Nullable<double> _DL覆盖11;
		
		private System.Nullable<double> _DL覆盖12;
		
		private System.Nullable<double> _DL覆盖13;
		
		private System.Nullable<double> _DL覆盖14;
		
		private System.Nullable<double> _DL覆盖15;
		
		private System.Nullable<double> _DL覆盖16;
		
		private System.Nullable<double> _DL覆盖17;
		
		private System.Nullable<double> _DL覆盖18;
		
		private System.Nullable<double> _DL覆盖19;
		
		private System.Nullable<double> _DL覆盖20;
		
		private System.Nullable<double> _DL覆盖21;
		
		private System.Nullable<double> _DL覆盖22;
		
		private System.Nullable<double> _DL覆盖23;
		
		private System.Nullable<double> _DL覆盖24;
		
		private System.Nullable<double> _DL覆盖25;
		
		private System.Nullable<double> _DL覆盖26;
		
		private System.Nullable<double> _DL覆盖27;
		
		private System.Nullable<double> _DL覆盖28;
		
		private System.Nullable<double> _DL覆盖29;
		
		private System.Nullable<double> _DL覆盖30;
		
		private System.Nullable<double> _DL覆盖31;
		
		private System.Nullable<double> _DL覆盖32;
		
		private System.Nullable<double> _DL覆盖33;
		
		private System.Nullable<double> _DL覆盖34;
		
		private System.Nullable<double> _DL覆盖35;
		
		private System.Nullable<double> _DL覆盖36;
		
		private System.Nullable<double> _DL覆盖37;
		
		private System.Nullable<double> _DL覆盖38;
		
		private System.Nullable<double> _DL覆盖39;
		
		private System.Nullable<double> _DL覆盖40;
		
		private System.Nullable<double> _DL覆盖41;
		
		private System.Nullable<double> _DL覆盖42;
		
		private System.Nullable<double> _DL覆盖43;
		
		private System.Nullable<double> _DL覆盖44;
		
		private System.Nullable<double> _DL覆盖45;
		
		private System.Nullable<double> _DL覆盖46;
		
		private System.Nullable<double> _DL覆盖47;
		
		private System.Nullable<double> _DL覆盖48;
		
		private System.Nullable<double> _DL覆盖49;
		
		private System.Nullable<double> _DL覆盖50;
		
		private System.Nullable<double> _DL覆盖51;
		
		private System.Nullable<double> _DL覆盖52;
		
		private System.Nullable<double> _DL覆盖53;
		
		private System.Nullable<double> _DL覆盖54;
		
		private System.Nullable<double> _DL覆盖55;
		
		private System.Nullable<double> _DL覆盖56;
		
		private System.Nullable<double> _DL覆盖57;
		
		private System.Nullable<double> _DL覆盖58;
		
		private System.Nullable<double> _DL覆盖59;
		
		private System.Nullable<double> _DL覆盖60;
		
		private System.Nullable<double> _DL覆盖61;
		
		private System.Nullable<double> _DL覆盖62;
		
		private System.Nullable<double> _DL覆盖63;
		
		public MRR_0822()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时间", DbType="DateTime")]
		public System.Nullable<System.DateTime> 时间
		{
			get
			{
				return this._时间;
			}
			set
			{
				if ((this._时间 != value))
				{
					this._时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区名", DbType="NVarChar(254)")]
		public string 小区名
		{
			get
			{
				return this._小区名;
			}
			set
			{
				if ((this._小区名 != value))
				{
					this._小区名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖94", DbType="Float")]
		public System.Nullable<double> DL覆盖94
		{
			get
			{
				return this._DL覆盖94;
			}
			set
			{
				if ((this._DL覆盖94 != value))
				{
					this._DL覆盖94 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖90", DbType="Float")]
		public System.Nullable<double> DL覆盖90
		{
			get
			{
				return this._DL覆盖90;
			}
			set
			{
				if ((this._DL覆盖90 != value))
				{
					this._DL覆盖90 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖85", DbType="Float")]
		public System.Nullable<double> DL覆盖85
		{
			get
			{
				return this._DL覆盖85;
			}
			set
			{
				if ((this._DL覆盖85 != value))
				{
					this._DL覆盖85 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖75", DbType="Float")]
		public System.Nullable<double> DL覆盖75
		{
			get
			{
				return this._DL覆盖75;
			}
			set
			{
				if ((this._DL覆盖75 != value))
				{
					this._DL覆盖75 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖采样数", DbType="Int")]
		public System.Nullable<int> DL覆盖采样数
		{
			get
			{
				return this._DL覆盖采样数;
			}
			set
			{
				if ((this._DL覆盖采样数 != value))
				{
					this._DL覆盖采样数 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖0", DbType="Float")]
		public System.Nullable<double> DL覆盖0
		{
			get
			{
				return this._DL覆盖0;
			}
			set
			{
				if ((this._DL覆盖0 != value))
				{
					this._DL覆盖0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖1", DbType="Float")]
		public System.Nullable<double> DL覆盖1
		{
			get
			{
				return this._DL覆盖1;
			}
			set
			{
				if ((this._DL覆盖1 != value))
				{
					this._DL覆盖1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖2", DbType="Float")]
		public System.Nullable<double> DL覆盖2
		{
			get
			{
				return this._DL覆盖2;
			}
			set
			{
				if ((this._DL覆盖2 != value))
				{
					this._DL覆盖2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖3", DbType="Float")]
		public System.Nullable<double> DL覆盖3
		{
			get
			{
				return this._DL覆盖3;
			}
			set
			{
				if ((this._DL覆盖3 != value))
				{
					this._DL覆盖3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖4", DbType="Float")]
		public System.Nullable<double> DL覆盖4
		{
			get
			{
				return this._DL覆盖4;
			}
			set
			{
				if ((this._DL覆盖4 != value))
				{
					this._DL覆盖4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖5", DbType="Float")]
		public System.Nullable<double> DL覆盖5
		{
			get
			{
				return this._DL覆盖5;
			}
			set
			{
				if ((this._DL覆盖5 != value))
				{
					this._DL覆盖5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖6", DbType="Float")]
		public System.Nullable<double> DL覆盖6
		{
			get
			{
				return this._DL覆盖6;
			}
			set
			{
				if ((this._DL覆盖6 != value))
				{
					this._DL覆盖6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖7", DbType="Float")]
		public System.Nullable<double> DL覆盖7
		{
			get
			{
				return this._DL覆盖7;
			}
			set
			{
				if ((this._DL覆盖7 != value))
				{
					this._DL覆盖7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖8", DbType="Float")]
		public System.Nullable<double> DL覆盖8
		{
			get
			{
				return this._DL覆盖8;
			}
			set
			{
				if ((this._DL覆盖8 != value))
				{
					this._DL覆盖8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖9", DbType="Float")]
		public System.Nullable<double> DL覆盖9
		{
			get
			{
				return this._DL覆盖9;
			}
			set
			{
				if ((this._DL覆盖9 != value))
				{
					this._DL覆盖9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖10", DbType="Float")]
		public System.Nullable<double> DL覆盖10
		{
			get
			{
				return this._DL覆盖10;
			}
			set
			{
				if ((this._DL覆盖10 != value))
				{
					this._DL覆盖10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖11", DbType="Float")]
		public System.Nullable<double> DL覆盖11
		{
			get
			{
				return this._DL覆盖11;
			}
			set
			{
				if ((this._DL覆盖11 != value))
				{
					this._DL覆盖11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖12", DbType="Float")]
		public System.Nullable<double> DL覆盖12
		{
			get
			{
				return this._DL覆盖12;
			}
			set
			{
				if ((this._DL覆盖12 != value))
				{
					this._DL覆盖12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖13", DbType="Float")]
		public System.Nullable<double> DL覆盖13
		{
			get
			{
				return this._DL覆盖13;
			}
			set
			{
				if ((this._DL覆盖13 != value))
				{
					this._DL覆盖13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖14", DbType="Float")]
		public System.Nullable<double> DL覆盖14
		{
			get
			{
				return this._DL覆盖14;
			}
			set
			{
				if ((this._DL覆盖14 != value))
				{
					this._DL覆盖14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖15", DbType="Float")]
		public System.Nullable<double> DL覆盖15
		{
			get
			{
				return this._DL覆盖15;
			}
			set
			{
				if ((this._DL覆盖15 != value))
				{
					this._DL覆盖15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖16", DbType="Float")]
		public System.Nullable<double> DL覆盖16
		{
			get
			{
				return this._DL覆盖16;
			}
			set
			{
				if ((this._DL覆盖16 != value))
				{
					this._DL覆盖16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖17", DbType="Float")]
		public System.Nullable<double> DL覆盖17
		{
			get
			{
				return this._DL覆盖17;
			}
			set
			{
				if ((this._DL覆盖17 != value))
				{
					this._DL覆盖17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖18", DbType="Float")]
		public System.Nullable<double> DL覆盖18
		{
			get
			{
				return this._DL覆盖18;
			}
			set
			{
				if ((this._DL覆盖18 != value))
				{
					this._DL覆盖18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖19", DbType="Float")]
		public System.Nullable<double> DL覆盖19
		{
			get
			{
				return this._DL覆盖19;
			}
			set
			{
				if ((this._DL覆盖19 != value))
				{
					this._DL覆盖19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖20", DbType="Float")]
		public System.Nullable<double> DL覆盖20
		{
			get
			{
				return this._DL覆盖20;
			}
			set
			{
				if ((this._DL覆盖20 != value))
				{
					this._DL覆盖20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖21", DbType="Float")]
		public System.Nullable<double> DL覆盖21
		{
			get
			{
				return this._DL覆盖21;
			}
			set
			{
				if ((this._DL覆盖21 != value))
				{
					this._DL覆盖21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖22", DbType="Float")]
		public System.Nullable<double> DL覆盖22
		{
			get
			{
				return this._DL覆盖22;
			}
			set
			{
				if ((this._DL覆盖22 != value))
				{
					this._DL覆盖22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖23", DbType="Float")]
		public System.Nullable<double> DL覆盖23
		{
			get
			{
				return this._DL覆盖23;
			}
			set
			{
				if ((this._DL覆盖23 != value))
				{
					this._DL覆盖23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖24", DbType="Float")]
		public System.Nullable<double> DL覆盖24
		{
			get
			{
				return this._DL覆盖24;
			}
			set
			{
				if ((this._DL覆盖24 != value))
				{
					this._DL覆盖24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖25", DbType="Float")]
		public System.Nullable<double> DL覆盖25
		{
			get
			{
				return this._DL覆盖25;
			}
			set
			{
				if ((this._DL覆盖25 != value))
				{
					this._DL覆盖25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖26", DbType="Float")]
		public System.Nullable<double> DL覆盖26
		{
			get
			{
				return this._DL覆盖26;
			}
			set
			{
				if ((this._DL覆盖26 != value))
				{
					this._DL覆盖26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖27", DbType="Float")]
		public System.Nullable<double> DL覆盖27
		{
			get
			{
				return this._DL覆盖27;
			}
			set
			{
				if ((this._DL覆盖27 != value))
				{
					this._DL覆盖27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖28", DbType="Float")]
		public System.Nullable<double> DL覆盖28
		{
			get
			{
				return this._DL覆盖28;
			}
			set
			{
				if ((this._DL覆盖28 != value))
				{
					this._DL覆盖28 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖29", DbType="Float")]
		public System.Nullable<double> DL覆盖29
		{
			get
			{
				return this._DL覆盖29;
			}
			set
			{
				if ((this._DL覆盖29 != value))
				{
					this._DL覆盖29 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖30", DbType="Float")]
		public System.Nullable<double> DL覆盖30
		{
			get
			{
				return this._DL覆盖30;
			}
			set
			{
				if ((this._DL覆盖30 != value))
				{
					this._DL覆盖30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖31", DbType="Float")]
		public System.Nullable<double> DL覆盖31
		{
			get
			{
				return this._DL覆盖31;
			}
			set
			{
				if ((this._DL覆盖31 != value))
				{
					this._DL覆盖31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖32", DbType="Float")]
		public System.Nullable<double> DL覆盖32
		{
			get
			{
				return this._DL覆盖32;
			}
			set
			{
				if ((this._DL覆盖32 != value))
				{
					this._DL覆盖32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖33", DbType="Float")]
		public System.Nullable<double> DL覆盖33
		{
			get
			{
				return this._DL覆盖33;
			}
			set
			{
				if ((this._DL覆盖33 != value))
				{
					this._DL覆盖33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖34", DbType="Float")]
		public System.Nullable<double> DL覆盖34
		{
			get
			{
				return this._DL覆盖34;
			}
			set
			{
				if ((this._DL覆盖34 != value))
				{
					this._DL覆盖34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖35", DbType="Float")]
		public System.Nullable<double> DL覆盖35
		{
			get
			{
				return this._DL覆盖35;
			}
			set
			{
				if ((this._DL覆盖35 != value))
				{
					this._DL覆盖35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖36", DbType="Float")]
		public System.Nullable<double> DL覆盖36
		{
			get
			{
				return this._DL覆盖36;
			}
			set
			{
				if ((this._DL覆盖36 != value))
				{
					this._DL覆盖36 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖37", DbType="Float")]
		public System.Nullable<double> DL覆盖37
		{
			get
			{
				return this._DL覆盖37;
			}
			set
			{
				if ((this._DL覆盖37 != value))
				{
					this._DL覆盖37 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖38", DbType="Float")]
		public System.Nullable<double> DL覆盖38
		{
			get
			{
				return this._DL覆盖38;
			}
			set
			{
				if ((this._DL覆盖38 != value))
				{
					this._DL覆盖38 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖39", DbType="Float")]
		public System.Nullable<double> DL覆盖39
		{
			get
			{
				return this._DL覆盖39;
			}
			set
			{
				if ((this._DL覆盖39 != value))
				{
					this._DL覆盖39 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖40", DbType="Float")]
		public System.Nullable<double> DL覆盖40
		{
			get
			{
				return this._DL覆盖40;
			}
			set
			{
				if ((this._DL覆盖40 != value))
				{
					this._DL覆盖40 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖41", DbType="Float")]
		public System.Nullable<double> DL覆盖41
		{
			get
			{
				return this._DL覆盖41;
			}
			set
			{
				if ((this._DL覆盖41 != value))
				{
					this._DL覆盖41 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖42", DbType="Float")]
		public System.Nullable<double> DL覆盖42
		{
			get
			{
				return this._DL覆盖42;
			}
			set
			{
				if ((this._DL覆盖42 != value))
				{
					this._DL覆盖42 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖43", DbType="Float")]
		public System.Nullable<double> DL覆盖43
		{
			get
			{
				return this._DL覆盖43;
			}
			set
			{
				if ((this._DL覆盖43 != value))
				{
					this._DL覆盖43 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖44", DbType="Float")]
		public System.Nullable<double> DL覆盖44
		{
			get
			{
				return this._DL覆盖44;
			}
			set
			{
				if ((this._DL覆盖44 != value))
				{
					this._DL覆盖44 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖45", DbType="Float")]
		public System.Nullable<double> DL覆盖45
		{
			get
			{
				return this._DL覆盖45;
			}
			set
			{
				if ((this._DL覆盖45 != value))
				{
					this._DL覆盖45 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖46", DbType="Float")]
		public System.Nullable<double> DL覆盖46
		{
			get
			{
				return this._DL覆盖46;
			}
			set
			{
				if ((this._DL覆盖46 != value))
				{
					this._DL覆盖46 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖47", DbType="Float")]
		public System.Nullable<double> DL覆盖47
		{
			get
			{
				return this._DL覆盖47;
			}
			set
			{
				if ((this._DL覆盖47 != value))
				{
					this._DL覆盖47 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖48", DbType="Float")]
		public System.Nullable<double> DL覆盖48
		{
			get
			{
				return this._DL覆盖48;
			}
			set
			{
				if ((this._DL覆盖48 != value))
				{
					this._DL覆盖48 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖49", DbType="Float")]
		public System.Nullable<double> DL覆盖49
		{
			get
			{
				return this._DL覆盖49;
			}
			set
			{
				if ((this._DL覆盖49 != value))
				{
					this._DL覆盖49 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖50", DbType="Float")]
		public System.Nullable<double> DL覆盖50
		{
			get
			{
				return this._DL覆盖50;
			}
			set
			{
				if ((this._DL覆盖50 != value))
				{
					this._DL覆盖50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖51", DbType="Float")]
		public System.Nullable<double> DL覆盖51
		{
			get
			{
				return this._DL覆盖51;
			}
			set
			{
				if ((this._DL覆盖51 != value))
				{
					this._DL覆盖51 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖52", DbType="Float")]
		public System.Nullable<double> DL覆盖52
		{
			get
			{
				return this._DL覆盖52;
			}
			set
			{
				if ((this._DL覆盖52 != value))
				{
					this._DL覆盖52 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖53", DbType="Float")]
		public System.Nullable<double> DL覆盖53
		{
			get
			{
				return this._DL覆盖53;
			}
			set
			{
				if ((this._DL覆盖53 != value))
				{
					this._DL覆盖53 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖54", DbType="Float")]
		public System.Nullable<double> DL覆盖54
		{
			get
			{
				return this._DL覆盖54;
			}
			set
			{
				if ((this._DL覆盖54 != value))
				{
					this._DL覆盖54 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖55", DbType="Float")]
		public System.Nullable<double> DL覆盖55
		{
			get
			{
				return this._DL覆盖55;
			}
			set
			{
				if ((this._DL覆盖55 != value))
				{
					this._DL覆盖55 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖56", DbType="Float")]
		public System.Nullable<double> DL覆盖56
		{
			get
			{
				return this._DL覆盖56;
			}
			set
			{
				if ((this._DL覆盖56 != value))
				{
					this._DL覆盖56 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖57", DbType="Float")]
		public System.Nullable<double> DL覆盖57
		{
			get
			{
				return this._DL覆盖57;
			}
			set
			{
				if ((this._DL覆盖57 != value))
				{
					this._DL覆盖57 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖58", DbType="Float")]
		public System.Nullable<double> DL覆盖58
		{
			get
			{
				return this._DL覆盖58;
			}
			set
			{
				if ((this._DL覆盖58 != value))
				{
					this._DL覆盖58 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖59", DbType="Float")]
		public System.Nullable<double> DL覆盖59
		{
			get
			{
				return this._DL覆盖59;
			}
			set
			{
				if ((this._DL覆盖59 != value))
				{
					this._DL覆盖59 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖60", DbType="Float")]
		public System.Nullable<double> DL覆盖60
		{
			get
			{
				return this._DL覆盖60;
			}
			set
			{
				if ((this._DL覆盖60 != value))
				{
					this._DL覆盖60 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖61", DbType="Float")]
		public System.Nullable<double> DL覆盖61
		{
			get
			{
				return this._DL覆盖61;
			}
			set
			{
				if ((this._DL覆盖61 != value))
				{
					this._DL覆盖61 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖62", DbType="Float")]
		public System.Nullable<double> DL覆盖62
		{
			get
			{
				return this._DL覆盖62;
			}
			set
			{
				if ((this._DL覆盖62 != value))
				{
					this._DL覆盖62 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL覆盖63", DbType="Float")]
		public System.Nullable<double> DL覆盖63
		{
			get
			{
				return this._DL覆盖63;
			}
			set
			{
				if ((this._DL覆盖63 != value))
				{
					this._DL覆盖63 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.现网cdd_0822")]
	public partial class 现网cdd_0822
	{
		
		private System.Nullable<int> _cellid;
		
		private string _cell_name;
		
		private System.Nullable<int> _accmin;
		
		private System.Nullable<int> _cchpwr;
		
		private System.Nullable<int> _cro;
		
		private System.Nullable<int> _pt;
		
		private System.Nullable<int> _to;
		
		private string _CELL;
		
		private string _SITE;
		
		private string _BSC;
		
		private string _NW;
		
		private string _MSC;
		
		private System.Nullable<System.DateTime> _CDate;
		
		public 现网cdd_0822()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cellid", DbType="Int")]
		public System.Nullable<int> cellid
		{
			get
			{
				return this._cellid;
			}
			set
			{
				if ((this._cellid != value))
				{
					this._cellid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="NVarChar(254)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this._cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accmin", DbType="Int")]
		public System.Nullable<int> accmin
		{
			get
			{
				return this._accmin;
			}
			set
			{
				if ((this._accmin != value))
				{
					this._accmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cchpwr", DbType="Int")]
		public System.Nullable<int> cchpwr
		{
			get
			{
				return this._cchpwr;
			}
			set
			{
				if ((this._cchpwr != value))
				{
					this._cchpwr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cro", DbType="Int")]
		public System.Nullable<int> cro
		{
			get
			{
				return this._cro;
			}
			set
			{
				if ((this._cro != value))
				{
					this._cro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt", DbType="Int")]
		public System.Nullable<int> pt
		{
			get
			{
				return this._pt;
			}
			set
			{
				if ((this._pt != value))
				{
					this._pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[to]", Storage="_to", DbType="Int")]
		public System.Nullable<int> to
		{
			get
			{
				return this._to;
			}
			set
			{
				if ((this._to != value))
				{
					this._to = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="NVarChar(254)")]
		public string CELL
		{
			get
			{
				return this._CELL;
			}
			set
			{
				if ((this._CELL != value))
				{
					this._CELL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="NVarChar(254)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NW", DbType="NVarChar(254)")]
		public string NW
		{
			get
			{
				return this._NW;
			}
			set
			{
				if ((this._NW != value))
				{
					this._NW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSC", DbType="NVarChar(254)")]
		public string MSC
		{
			get
			{
				return this._MSC;
			}
			set
			{
				if ((this._MSC != value))
				{
					this._MSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CDate
		{
			get
			{
				return this._CDate;
			}
			set
			{
				if ((this._CDate != value))
				{
					this._CDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.现网cdd_Nrel_0822")]
	public partial class 现网cdd_Nrel_0822
	{
		
		private System.Nullable<System.DateTime> _CDate;
		
		private string _NW;
		
		private string _MSC;
		
		private string _BSC;
		
		private string _SITE;
		
		private string _CELL;
		
		private System.Nullable<int> _cellid;
		
		private string _cell_name;
		
		private string _n_cell;
		
		private System.Nullable<int> _n_cellid;
		
		private string _n_cell_name;
		
		private string _n_bsc;
		
		private System.Nullable<int> _awoffset;
		
		private System.Nullable<int> _bqoffset;
		
		private System.Nullable<int> _bqoffsetafr;
		
		private string _cand;
		
		private string _cs;
		
		private string _gprsvalid;
		
		private System.Nullable<int> _hihyst;
		
		private System.Nullable<int> _khyst;
		
		private System.Nullable<int> _koffset;
		
		private System.Nullable<int> _lhyst;
		
		private System.Nullable<int> _loffset;
		
		private System.Nullable<int> _lohyst;
		
		private System.Nullable<int> _offset;
		
		private string _proffset;
		
		private System.Nullable<int> _trhyst;
		
		private System.Nullable<int> _troffset;
		
		public 现网cdd_Nrel_0822()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CDate
		{
			get
			{
				return this._CDate;
			}
			set
			{
				if ((this._CDate != value))
				{
					this._CDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NW", DbType="NVarChar(254)")]
		public string NW
		{
			get
			{
				return this._NW;
			}
			set
			{
				if ((this._NW != value))
				{
					this._NW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSC", DbType="NVarChar(254)")]
		public string MSC
		{
			get
			{
				return this._MSC;
			}
			set
			{
				if ((this._MSC != value))
				{
					this._MSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="NVarChar(254)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="NVarChar(254)")]
		public string CELL
		{
			get
			{
				return this._CELL;
			}
			set
			{
				if ((this._CELL != value))
				{
					this._CELL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cellid", DbType="Int")]
		public System.Nullable<int> cellid
		{
			get
			{
				return this._cellid;
			}
			set
			{
				if ((this._cellid != value))
				{
					this._cellid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="NVarChar(254)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this._cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_cell", DbType="NVarChar(254)")]
		public string n_cell
		{
			get
			{
				return this._n_cell;
			}
			set
			{
				if ((this._n_cell != value))
				{
					this._n_cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_cellid", DbType="Int")]
		public System.Nullable<int> n_cellid
		{
			get
			{
				return this._n_cellid;
			}
			set
			{
				if ((this._n_cellid != value))
				{
					this._n_cellid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_cell_name", DbType="NVarChar(254)")]
		public string n_cell_name
		{
			get
			{
				return this._n_cell_name;
			}
			set
			{
				if ((this._n_cell_name != value))
				{
					this._n_cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_bsc", DbType="NVarChar(254)")]
		public string n_bsc
		{
			get
			{
				return this._n_bsc;
			}
			set
			{
				if ((this._n_bsc != value))
				{
					this._n_bsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_awoffset", DbType="Int")]
		public System.Nullable<int> awoffset
		{
			get
			{
				return this._awoffset;
			}
			set
			{
				if ((this._awoffset != value))
				{
					this._awoffset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqoffset", DbType="Int")]
		public System.Nullable<int> bqoffset
		{
			get
			{
				return this._bqoffset;
			}
			set
			{
				if ((this._bqoffset != value))
				{
					this._bqoffset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqoffsetafr", DbType="Int")]
		public System.Nullable<int> bqoffsetafr
		{
			get
			{
				return this._bqoffsetafr;
			}
			set
			{
				if ((this._bqoffsetafr != value))
				{
					this._bqoffsetafr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cand", DbType="NVarChar(254)")]
		public string cand
		{
			get
			{
				return this._cand;
			}
			set
			{
				if ((this._cand != value))
				{
					this._cand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs", DbType="NVarChar(254)")]
		public string cs
		{
			get
			{
				return this._cs;
			}
			set
			{
				if ((this._cs != value))
				{
					this._cs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gprsvalid", DbType="NVarChar(254)")]
		public string gprsvalid
		{
			get
			{
				return this._gprsvalid;
			}
			set
			{
				if ((this._gprsvalid != value))
				{
					this._gprsvalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hihyst", DbType="Int")]
		public System.Nullable<int> hihyst
		{
			get
			{
				return this._hihyst;
			}
			set
			{
				if ((this._hihyst != value))
				{
					this._hihyst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khyst", DbType="Int")]
		public System.Nullable<int> khyst
		{
			get
			{
				return this._khyst;
			}
			set
			{
				if ((this._khyst != value))
				{
					this._khyst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_koffset", DbType="Int")]
		public System.Nullable<int> koffset
		{
			get
			{
				return this._koffset;
			}
			set
			{
				if ((this._koffset != value))
				{
					this._koffset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lhyst", DbType="Int")]
		public System.Nullable<int> lhyst
		{
			get
			{
				return this._lhyst;
			}
			set
			{
				if ((this._lhyst != value))
				{
					this._lhyst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loffset", DbType="Int")]
		public System.Nullable<int> loffset
		{
			get
			{
				return this._loffset;
			}
			set
			{
				if ((this._loffset != value))
				{
					this._loffset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lohyst", DbType="Int")]
		public System.Nullable<int> lohyst
		{
			get
			{
				return this._lohyst;
			}
			set
			{
				if ((this._lohyst != value))
				{
					this._lohyst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offset", DbType="Int")]
		public System.Nullable<int> offset
		{
			get
			{
				return this._offset;
			}
			set
			{
				if ((this._offset != value))
				{
					this._offset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proffset", DbType="NVarChar(254)")]
		public string proffset
		{
			get
			{
				return this._proffset;
			}
			set
			{
				if ((this._proffset != value))
				{
					this._proffset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trhyst", DbType="Int")]
		public System.Nullable<int> trhyst
		{
			get
			{
				return this._trhyst;
			}
			set
			{
				if ((this._trhyst != value))
				{
					this._trhyst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_troffset", DbType="Int")]
		public System.Nullable<int> troffset
		{
			get
			{
				return this._troffset;
			}
			set
			{
				if ((this._troffset != value))
				{
					this._troffset = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.小区基础数据_0822")]
	public partial class 小区基础数据_0822
	{
		
		private string _小区名;
		
		private string _小区号;
		
		private string _状态;
		
		private string _基站名;
		
		private string _BSC;
		
		private string _LAI;
		
		private string _CI;
		
		private System.Nullable<double> _经度;
		
		private System.Nullable<double> _纬度;
		
		private string _详细地址;
		
		private System.Nullable<int> _方向角;
		
		private System.Nullable<int> _下倾角;
		
		private System.Nullable<int> _相对高度;
		
		private System.Nullable<int> _海拔高度;
		
		private System.Nullable<int> _功分编号;
		
		private System.Nullable<int> _天线数目;
		
		public 小区基础数据_0822()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区名", DbType="NVarChar(254)")]
		public string 小区名
		{
			get
			{
				return this._小区名;
			}
			set
			{
				if ((this._小区名 != value))
				{
					this._小区名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区号", DbType="NVarChar(254)")]
		public string 小区号
		{
			get
			{
				return this._小区号;
			}
			set
			{
				if ((this._小区号 != value))
				{
					this._小区号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_状态", DbType="NVarChar(254)")]
		public string 状态
		{
			get
			{
				return this._状态;
			}
			set
			{
				if ((this._状态 != value))
				{
					this._状态 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_基站名", DbType="NVarChar(254)")]
		public string 基站名
		{
			get
			{
				return this._基站名;
			}
			set
			{
				if ((this._基站名 != value))
				{
					this._基站名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAI", DbType="NVarChar(254)")]
		public string LAI
		{
			get
			{
				return this._LAI;
			}
			set
			{
				if ((this._LAI != value))
				{
					this._LAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="NVarChar(254)")]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this._CI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_经度", DbType="Float")]
		public System.Nullable<double> 经度
		{
			get
			{
				return this._经度;
			}
			set
			{
				if ((this._经度 != value))
				{
					this._经度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_纬度", DbType="Float")]
		public System.Nullable<double> 纬度
		{
			get
			{
				return this._纬度;
			}
			set
			{
				if ((this._纬度 != value))
				{
					this._纬度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_详细地址", DbType="NVarChar(254)")]
		public string 详细地址
		{
			get
			{
				return this._详细地址;
			}
			set
			{
				if ((this._详细地址 != value))
				{
					this._详细地址 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_方向角", DbType="Int")]
		public System.Nullable<int> 方向角
		{
			get
			{
				return this._方向角;
			}
			set
			{
				if ((this._方向角 != value))
				{
					this._方向角 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_下倾角", DbType="Int")]
		public System.Nullable<int> 下倾角
		{
			get
			{
				return this._下倾角;
			}
			set
			{
				if ((this._下倾角 != value))
				{
					this._下倾角 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_相对高度", DbType="Int")]
		public System.Nullable<int> 相对高度
		{
			get
			{
				return this._相对高度;
			}
			set
			{
				if ((this._相对高度 != value))
				{
					this._相对高度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_海拔高度", DbType="Int")]
		public System.Nullable<int> 海拔高度
		{
			get
			{
				return this._海拔高度;
			}
			set
			{
				if ((this._海拔高度 != value))
				{
					this._海拔高度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_功分编号", DbType="Int")]
		public System.Nullable<int> 功分编号
		{
			get
			{
				return this._功分编号;
			}
			set
			{
				if ((this._功分编号 != value))
				{
					this._功分编号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_天线数目", DbType="Int")]
		public System.Nullable<int> 天线数目
		{
			get
			{
				return this._天线数目;
			}
			set
			{
				if ((this._天线数目 != value))
				{
					this._天线数目 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.小区切换查询_0822_1")]
	public partial class 小区切换查询_0822_1
	{
		
		private System.Nullable<int> _切换次数;
		
		private string _小区名;
		
		private string _邻小区名;
		
		public 小区切换查询_0822_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_切换次数", DbType="Int")]
		public System.Nullable<int> 切换次数
		{
			get
			{
				return this._切换次数;
			}
			set
			{
				if ((this._切换次数 != value))
				{
					this._切换次数 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区名", DbType="NVarChar(254)")]
		public string 小区名
		{
			get
			{
				return this._小区名;
			}
			set
			{
				if ((this._小区名 != value))
				{
					this._小区名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_邻小区名", DbType="NVarChar(254)")]
		public string 邻小区名
		{
			get
			{
				return this._邻小区名;
			}
			set
			{
				if ((this._邻小区名 != value))
				{
					this._邻小区名 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CELLGPRS_0902_1")]
	public partial class CELLGPRS_0902_1
	{
		
		private System.Nullable<System.DateTime> _时间;
		
		private string _小区名;
		
		private string _小区号;
		
		private string _BSC;
		
		private System.Nullable<double> _下行TBF建立成功率;
		
		private System.Nullable<double> _EDGE每线下行激活用户;
		
		private System.Nullable<double> _GPRS每线下行激活用户;
		
		private System.Nullable<double> _平均分配PDCH;
		
		private System.Nullable<double> _GPRS下行激活信道;
		
		private System.Nullable<double> _EDGE下行激活信道;
		
		private System.Nullable<double> _EDGE每线下行用户;
		
		private System.Nullable<double> _EDGE终端使用EDGE比例;
		
		private System.Nullable<double> _GPRS每线下行用户;
		
		private System.Nullable<int> _T可用信道;
		
		private System.Nullable<double> _T话务量;
		
		private System.Nullable<double> _H话务比;
		
		private System.Nullable<int> _FAILDLTBFEST;
		
		private System.Nullable<double> _PDCH复用度;
		
		public CELLGPRS_0902_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时间", DbType="DateTime")]
		public System.Nullable<System.DateTime> 时间
		{
			get
			{
				return this._时间;
			}
			set
			{
				if ((this._时间 != value))
				{
					this._时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区名", DbType="NVarChar(254)")]
		public string 小区名
		{
			get
			{
				return this._小区名;
			}
			set
			{
				if ((this._小区名 != value))
				{
					this._小区名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_小区号", DbType="NVarChar(254)")]
		public string 小区号
		{
			get
			{
				return this._小区号;
			}
			set
			{
				if ((this._小区号 != value))
				{
					this._小区号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_下行TBF建立成功率", DbType="Float")]
		public System.Nullable<double> 下行TBF建立成功率
		{
			get
			{
				return this._下行TBF建立成功率;
			}
			set
			{
				if ((this._下行TBF建立成功率 != value))
				{
					this._下行TBF建立成功率 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE每线下行激活用户", DbType="Float")]
		public System.Nullable<double> EDGE每线下行激活用户
		{
			get
			{
				return this._EDGE每线下行激活用户;
			}
			set
			{
				if ((this._EDGE每线下行激活用户 != value))
				{
					this._EDGE每线下行激活用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPRS每线下行激活用户", DbType="Float")]
		public System.Nullable<double> GPRS每线下行激活用户
		{
			get
			{
				return this._GPRS每线下行激活用户;
			}
			set
			{
				if ((this._GPRS每线下行激活用户 != value))
				{
					this._GPRS每线下行激活用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_平均分配PDCH", DbType="Float")]
		public System.Nullable<double> 平均分配PDCH
		{
			get
			{
				return this._平均分配PDCH;
			}
			set
			{
				if ((this._平均分配PDCH != value))
				{
					this._平均分配PDCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPRS下行激活信道", DbType="Float")]
		public System.Nullable<double> GPRS下行激活信道
		{
			get
			{
				return this._GPRS下行激活信道;
			}
			set
			{
				if ((this._GPRS下行激活信道 != value))
				{
					this._GPRS下行激活信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE下行激活信道", DbType="Float")]
		public System.Nullable<double> EDGE下行激活信道
		{
			get
			{
				return this._EDGE下行激活信道;
			}
			set
			{
				if ((this._EDGE下行激活信道 != value))
				{
					this._EDGE下行激活信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE每线下行用户", DbType="Float")]
		public System.Nullable<double> EDGE每线下行用户
		{
			get
			{
				return this._EDGE每线下行用户;
			}
			set
			{
				if ((this._EDGE每线下行用户 != value))
				{
					this._EDGE每线下行用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDGE终端使用EDGE比例", DbType="Float")]
		public System.Nullable<double> EDGE终端使用EDGE比例
		{
			get
			{
				return this._EDGE终端使用EDGE比例;
			}
			set
			{
				if ((this._EDGE终端使用EDGE比例 != value))
				{
					this._EDGE终端使用EDGE比例 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPRS每线下行用户", DbType="Float")]
		public System.Nullable<double> GPRS每线下行用户
		{
			get
			{
				return this._GPRS每线下行用户;
			}
			set
			{
				if ((this._GPRS每线下行用户 != value))
				{
					this._GPRS每线下行用户 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T可用信道", DbType="Int")]
		public System.Nullable<int> T可用信道
		{
			get
			{
				return this._T可用信道;
			}
			set
			{
				if ((this._T可用信道 != value))
				{
					this._T可用信道 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T话务量", DbType="Float")]
		public System.Nullable<double> T话务量
		{
			get
			{
				return this._T话务量;
			}
			set
			{
				if ((this._T话务量 != value))
				{
					this._T话务量 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H话务比", DbType="Float")]
		public System.Nullable<double> H话务比
		{
			get
			{
				return this._H话务比;
			}
			set
			{
				if ((this._H话务比 != value))
				{
					this._H话务比 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAILDLTBFEST", DbType="Int")]
		public System.Nullable<int> FAILDLTBFEST
		{
			get
			{
				return this._FAILDLTBFEST;
			}
			set
			{
				if ((this._FAILDLTBFEST != value))
				{
					this._FAILDLTBFEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDCH复用度", DbType="Float")]
		public System.Nullable<double> PDCH复用度
		{
			get
			{
				return this._PDCH复用度;
			}
			set
			{
				if ((this._PDCH复用度 != value))
				{
					this._PDCH复用度 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
