<?xml version="1.0" encoding="utf-8"?><Database Name="SqlSpatialJiangmeng" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=SqlSpatialJiangmeng;Integrated Security=True" SettingsObjectName="Linq2SqlGeography.Properties.Settings" SettingsPropertyName="SqlSpatialTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SITE" Member="SITE">
    <Type Name="SITE">
      <Column Name="msc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="bsc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cell" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="bts" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="lac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ci" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cell_name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="bts_name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tilt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ground_height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ant_bw" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ant_size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="band" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="power" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="half_power" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active_balist" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="idle_balist" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry"  CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CELLTRACING" Member="CELLTRACING">
    <Type Name="CELLTRACING">
      <Column Name="SiteName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry"  CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>