#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq2SqlGeography
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SqlSpatialJiangmeng")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSITE(SITE instance);
    partial void UpdateSITE(SITE instance);
    partial void DeleteSITE(SITE instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::Linq2SqlGeography.Properties.Settings.Default.SqlSpatialTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SITE> SITE
		{
			get
			{
				return this.GetTable<SITE>();
			}
		}
		
		public System.Data.Linq.Table<CELLTRACING> CELLTRACING
		{
			get
			{
				return this.GetTable<CELLTRACING>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SITE")]
	public partial class SITE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _msc;
		
		private string _bsc;
		
		private string _cell;
		
		private string _bts;
		
		private System.Nullable<int> _lac;
		
		private System.Nullable<int> _ci;
		
		private System.Nullable<int> _bcch;
		
		private System.Nullable<int> _bsic;
		
		private string _cell_name;
		
		private string _bts_name;
		
		private System.Nullable<decimal> _longitude;
		
		private System.Nullable<decimal> _latitude;
		
		private System.Nullable<int> _dir;
		
		private System.Nullable<int> _height;
		
		private System.Nullable<int> _tilt;
		
		private System.Nullable<int> _ground_height;
		
		private System.Nullable<int> _ant_bw;
		
		private System.Nullable<int> _ant_size;
		
		private string _band;
		
		private System.Nullable<int> _power;
		
		private System.Nullable<int> _half_power;
		
		private string _active_balist;
		
		private string _idle_balist;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmscChanging(string value);
    partial void OnmscChanged();
    partial void OnbscChanging(string value);
    partial void OnbscChanged();
    partial void OncellChanging(string value);
    partial void OncellChanged();
    partial void OnbtsChanging(string value);
    partial void OnbtsChanged();
    partial void OnlacChanging(System.Nullable<int> value);
    partial void OnlacChanged();
    partial void OnciChanging(System.Nullable<int> value);
    partial void OnciChanged();
    partial void OnbcchChanging(System.Nullable<int> value);
    partial void OnbcchChanged();
    partial void OnbsicChanging(System.Nullable<int> value);
    partial void OnbsicChanged();
    partial void Oncell_nameChanging(string value);
    partial void Oncell_nameChanged();
    partial void Onbts_nameChanging(string value);
    partial void Onbts_nameChanged();
    partial void OnlongitudeChanging(System.Nullable<decimal> value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(System.Nullable<decimal> value);
    partial void OnlatitudeChanged();
    partial void OndirChanging(System.Nullable<int> value);
    partial void OndirChanged();
    partial void OnheightChanging(System.Nullable<int> value);
    partial void OnheightChanged();
    partial void OntiltChanging(System.Nullable<int> value);
    partial void OntiltChanged();
    partial void Onground_heightChanging(System.Nullable<int> value);
    partial void Onground_heightChanged();
    partial void Onant_bwChanging(System.Nullable<int> value);
    partial void Onant_bwChanged();
    partial void Onant_sizeChanging(System.Nullable<int> value);
    partial void Onant_sizeChanged();
    partial void OnbandChanging(string value);
    partial void OnbandChanged();
    partial void OnpowerChanging(System.Nullable<int> value);
    partial void OnpowerChanged();
    partial void Onhalf_powerChanging(System.Nullable<int> value);
    partial void Onhalf_powerChanged();
    partial void Onactive_balistChanging(string value);
    partial void Onactive_balistChanged();
    partial void Onidle_balistChanging(string value);
    partial void Onidle_balistChanged();
    partial void OnMI_STYLEChanging(string value);
    partial void OnMI_STYLEChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    partial void OnSP_GEOMETRYChanging(Microsoft.SqlServer.Types.SqlGeometry value);
    partial void OnSP_GEOMETRYChanged();
    #endregion
		
		public SITE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msc", DbType="VarChar(10)")]
		public string msc
		{
			get
			{
				return this._msc;
			}
			set
			{
				if ((this._msc != value))
				{
					this.OnmscChanging(value);
					this.SendPropertyChanging();
					this._msc = value;
					this.SendPropertyChanged("msc");
					this.OnmscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsc", DbType="VarChar(10)")]
		public string bsc
		{
			get
			{
				return this._bsc;
			}
			set
			{
				if ((this._bsc != value))
				{
					this.OnbscChanging(value);
					this.SendPropertyChanging();
					this._bsc = value;
					this.SendPropertyChanged("bsc");
					this.OnbscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="VarChar(10)")]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this.OncellChanging(value);
					this.SendPropertyChanging();
					this._cell = value;
					this.SendPropertyChanged("cell");
					this.OncellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bts", DbType="VarChar(10)")]
		public string bts
		{
			get
			{
				return this._bts;
			}
			set
			{
				if ((this._bts != value))
				{
					this.OnbtsChanging(value);
					this.SendPropertyChanging();
					this._bts = value;
					this.SendPropertyChanged("bts");
					this.OnbtsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lac", DbType="Int")]
		public System.Nullable<int> lac
		{
			get
			{
				return this._lac;
			}
			set
			{
				if ((this._lac != value))
				{
					this.OnlacChanging(value);
					this.SendPropertyChanging();
					this._lac = value;
					this.SendPropertyChanged("lac");
					this.OnlacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="Int")]
		public System.Nullable<int> ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this.OnciChanging(value);
					this.SendPropertyChanging();
					this._ci = value;
					this.SendPropertyChanged("ci");
					this.OnciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch", DbType="Int")]
		public System.Nullable<int> bcch
		{
			get
			{
				return this._bcch;
			}
			set
			{
				if ((this._bcch != value))
				{
					this.OnbcchChanging(value);
					this.SendPropertyChanging();
					this._bcch = value;
					this.SendPropertyChanged("bcch");
					this.OnbcchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic", DbType="Int")]
		public System.Nullable<int> bsic
		{
			get
			{
				return this._bsic;
			}
			set
			{
				if ((this._bsic != value))
				{
					this.OnbsicChanging(value);
					this.SendPropertyChanging();
					this._bsic = value;
					this.SendPropertyChanged("bsic");
					this.OnbsicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="VarChar(30)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this.Oncell_nameChanging(value);
					this.SendPropertyChanging();
					this._cell_name = value;
					this.SendPropertyChanged("cell_name");
					this.Oncell_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bts_name", DbType="VarChar(30)")]
		public string bts_name
		{
			get
			{
				return this._bts_name;
			}
			set
			{
				if ((this._bts_name != value))
				{
					this.Onbts_nameChanging(value);
					this.SendPropertyChanging();
					this._bts_name = value;
					this.SendPropertyChanged("bts_name");
					this.Onbts_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir", DbType="Int")]
		public System.Nullable<int> dir
		{
			get
			{
				return this._dir;
			}
			set
			{
				if ((this._dir != value))
				{
					this.OndirChanging(value);
					this.SendPropertyChanging();
					this._dir = value;
					this.SendPropertyChanged("dir");
					this.OndirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int")]
		public System.Nullable<int> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilt", DbType="Int")]
		public System.Nullable<int> tilt
		{
			get
			{
				return this._tilt;
			}
			set
			{
				if ((this._tilt != value))
				{
					this.OntiltChanging(value);
					this.SendPropertyChanging();
					this._tilt = value;
					this.SendPropertyChanged("tilt");
					this.OntiltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ground_height", DbType="Int")]
		public System.Nullable<int> ground_height
		{
			get
			{
				return this._ground_height;
			}
			set
			{
				if ((this._ground_height != value))
				{
					this.Onground_heightChanging(value);
					this.SendPropertyChanging();
					this._ground_height = value;
					this.SendPropertyChanged("ground_height");
					this.Onground_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_bw", DbType="Int")]
		public System.Nullable<int> ant_bw
		{
			get
			{
				return this._ant_bw;
			}
			set
			{
				if ((this._ant_bw != value))
				{
					this.Onant_bwChanging(value);
					this.SendPropertyChanging();
					this._ant_bw = value;
					this.SendPropertyChanged("ant_bw");
					this.Onant_bwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_size", DbType="Int")]
		public System.Nullable<int> ant_size
		{
			get
			{
				return this._ant_size;
			}
			set
			{
				if ((this._ant_size != value))
				{
					this.Onant_sizeChanging(value);
					this.SendPropertyChanging();
					this._ant_size = value;
					this.SendPropertyChanged("ant_size");
					this.Onant_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_band", DbType="VarChar(10)")]
		public string band
		{
			get
			{
				return this._band;
			}
			set
			{
				if ((this._band != value))
				{
					this.OnbandChanging(value);
					this.SendPropertyChanging();
					this._band = value;
					this.SendPropertyChanged("band");
					this.OnbandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="Int")]
		public System.Nullable<int> power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this.OnpowerChanging(value);
					this.SendPropertyChanging();
					this._power = value;
					this.SendPropertyChanged("power");
					this.OnpowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_power", DbType="Int")]
		public System.Nullable<int> half_power
		{
			get
			{
				return this._half_power;
			}
			set
			{
				if ((this._half_power != value))
				{
					this.Onhalf_powerChanging(value);
					this.SendPropertyChanging();
					this._half_power = value;
					this.SendPropertyChanged("half_power");
					this.Onhalf_powerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_balist", DbType="VarChar(254)")]
		public string active_balist
		{
			get
			{
				return this._active_balist;
			}
			set
			{
				if ((this._active_balist != value))
				{
					this.Onactive_balistChanging(value);
					this.SendPropertyChanging();
					this._active_balist = value;
					this.SendPropertyChanged("active_balist");
					this.Onactive_balistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idle_balist", DbType="VarChar(254)")]
		public string idle_balist
		{
			get
			{
				return this._idle_balist;
			}
			set
			{
				if ((this._idle_balist != value))
				{
					this.Onidle_balistChanging(value);
					this.SendPropertyChanging();
					this._idle_balist = value;
					this.SendPropertyChanged("idle_balist");
					this.Onidle_balistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this.OnMI_STYLEChanging(value);
					this.SendPropertyChanging();
					this._MI_STYLE = value;
					this.SendPropertyChanged("MI_STYLE");
					this.OnMI_STYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this.OnSP_GEOMETRYChanging(value);
					this.SendPropertyChanging();
					this._SP_GEOMETRY = value;
					this.SendPropertyChanged("SP_GEOMETRY");
					this.OnSP_GEOMETRYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CELLTRACING")]
	public partial class CELLTRACING
	{
		
		private string _SiteName;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
		public CELLTRACING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(30)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this._MI_STYLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this._MI_PRINX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this._SP_GEOMETRY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
