#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq2SqlGeography.SqlGeography
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SqlSpatialTest")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Linq2SqlGeography.Properties.Settings.Default.SqlSpatialTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sqlspatial> sqlspatial
		{
			get
			{
				return this.GetTable<sqlspatial>();
			}
		}
	}

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.MCOMSITE1")]
	public partial class sqlspatial
	{
		
		private string _Cell;
		
		private string _Site;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<short> _Dir;
		
		private System.Nullable<double> _Height;
		
		private System.Nullable<short> _Tilt;
		
		private System.Nullable<double> _Ground_Height;
		
		private string _Cell_Type;
		
		private string _Ant_Type;
		
		private System.Nullable<short> _Ant_BW;
		
		private string _Note;
		
		private string _SiteName;
		
		private string _Flag1;
		
		private string _Flag2;
		
		private string _Flag3;
		
		private string _Flag4;
		
		private string _Flag5;
		
		private string _CI;
		
		private string _BSC;
		
		private System.Nullable<short> _Ant_size;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
		public sqlspatial()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(10)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this._Cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="VarChar(20)")]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this._Site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="SmallInt")]
		public System.Nullable<short> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
		public System.Nullable<double> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tilt", DbType="SmallInt")]
		public System.Nullable<short> Tilt
		{
			get
			{
				return this._Tilt;
			}
			set
			{
				if ((this._Tilt != value))
				{
					this._Tilt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ground_Height", DbType="Float")]
		public System.Nullable<double> Ground_Height
		{
			get
			{
				return this._Ground_Height;
			}
			set
			{
				if ((this._Ground_Height != value))
				{
					this._Ground_Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell_Type", DbType="VarChar(20)")]
		public string Cell_Type
		{
			get
			{
				return this._Cell_Type;
			}
			set
			{
				if ((this._Cell_Type != value))
				{
					this._Cell_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ant_Type", DbType="VarChar(20)")]
		public string Ant_Type
		{
			get
			{
				return this._Ant_Type;
			}
			set
			{
				if ((this._Ant_Type != value))
				{
					this._Ant_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ant_BW", DbType="SmallInt")]
		public System.Nullable<short> Ant_BW
		{
			get
			{
				return this._Ant_BW;
			}
			set
			{
				if ((this._Ant_BW != value))
				{
					this._Ant_BW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="VarChar(30)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(30)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag1", DbType="VarChar(30)")]
		public string Flag1
		{
			get
			{
				return this._Flag1;
			}
			set
			{
				if ((this._Flag1 != value))
				{
					this._Flag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag2", DbType="VarChar(30)")]
		public string Flag2
		{
			get
			{
				return this._Flag2;
			}
			set
			{
				if ((this._Flag2 != value))
				{
					this._Flag2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag3", DbType="VarChar(30)")]
		public string Flag3
		{
			get
			{
				return this._Flag3;
			}
			set
			{
				if ((this._Flag3 != value))
				{
					this._Flag3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag4", DbType="VarChar(30)")]
		public string Flag4
		{
			get
			{
				return this._Flag4;
			}
			set
			{
				if ((this._Flag4 != value))
				{
					this._Flag4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag5", DbType="VarChar(30)")]
		public string Flag5
		{
			get
			{
				return this._Flag5;
			}
			set
			{
				if ((this._Flag5 != value))
				{
					this._Flag5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="VarChar(6)")]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this._CI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="VarChar(10)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ant_size", DbType="SmallInt")]
		public System.Nullable<short> Ant_size
		{
			get
			{
				return this._Ant_size;
			}
			set
			{
				if ((this._Ant_size != value))
				{
					this._Ant_size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this._MI_STYLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this._MI_PRINX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this._SP_GEOMETRY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
