<?xml version="1.0" encoding="utf-8"?><Database Name="SqlSpatialJiangmeng" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=SqlSpatialJiangmeng;Integrated Security=True" SettingsObjectName="Linq2SqlGeography.Properties.Settings" SettingsPropertyName="SqlSpatialTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CellTracing" Member="CellTracing">
    <Type Name="CellTracing">
      <Column Name="cell" Storage="_SiteName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.SITE" Member="SITE">
    <Type Name="SITE">
      <Column Name="msc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="bsc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="cell" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="cell_name" Type="System.String" DbType="VarChar(21)" CanBeNull="true" />
      <Column Name="longitude" Type="System.Decimal" DbType="Decimal(11,6)" CanBeNull="true" />
      <Column Name="latitude" Type="System.Decimal" DbType="Decimal(11,6)" CanBeNull="true" />
      <Column Name="band" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="arfcn" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="height" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="dir" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="tilt" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="ant_bw" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="power" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ant_gain" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="ant_type" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ant_size" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventLocating" Member="EventLocating">
    <Type Name="EventLocating">
      <Column Name="events" Storage="_SiteName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.城市内部主要交通干道" Member="城市内部主要交通干道">
    <Type Name="城市内部主要交通干道">
      <Column Name="编码" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.MCOMNEIGH" Member="MCOMNEIGH">
    <Type Name="MCOMNEIGH">
      <Column Name="Cell" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ncell" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MCOMCARRIER" Member="MCOMCARRIER">
    <Type Name="MCOMCARRIER">
      <Column Name="Cell" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BSC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LAI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="BCCH" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BSIC" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TCH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HOP" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HSN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Ant_size" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Font_size" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MI_STYLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="MI_PRINX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SP_GEOMETRY" Type="Microsoft.SqlServer.Types.SqlGeometry" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Abis_MR" Member="Abis_MR">
    <Type Name="Abis_MR">
      <Column Name="FileNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginFrameNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PacketTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[PacketTime(ms)]" Member="PacketTime_ms_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DumpFor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Measurement_Report" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Measurement_Report_time" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="cell" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="bs_power" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ms_power" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="act_ta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dtx_used" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="rxlev_full_serv_cell" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev_sub_serv_cell" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsic5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcch5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rxlev5" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>