#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq2SqlGeography.LinqSql.FromAbis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Abis_Ho> Abis_Ho
		{
			get
			{
				return this.GetTable<Abis_Ho>();
			}
		}
		
		public System.Data.Linq.Table<Abis_MR> Abis_MR
		{
			get
			{
				return this.GetTable<Abis_MR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abis_Ho")]
	public partial class Abis_Ho
	{
		
		private System.Nullable<int> _FileNum;
		
		private System.Nullable<int> _PacketNum;
		
		private System.Nullable<int> _BeginFrameNum;
		
		private System.Nullable<System.DateTime> _PacketTime;
		
		private System.Nullable<int> _PacketTime_ms_;
		
		private string _DumpFor;
		
		private System.Nullable<int> _Handover_Command;
		
		private string _Handover_Command_time;
		
		private string _Handover_Command_MsgType;
		
		private System.Nullable<int> _Handover_Command_RepeatCounter;
		
		private string _ncc;
		
		private string _bcc;
		
		private string _bcch_arfcn;
		
		private string _chd2_single_ch_ARFCN;
		
		public Abis_Ho()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNum", DbType="Int")]
		public System.Nullable<int> FileNum
		{
			get
			{
				return this._FileNum;
			}
			set
			{
				if ((this._FileNum != value))
				{
					this._FileNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketNum", DbType="Int")]
		public System.Nullable<int> PacketNum
		{
			get
			{
				return this._PacketNum;
			}
			set
			{
				if ((this._PacketNum != value))
				{
					this._PacketNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginFrameNum", DbType="Int")]
		public System.Nullable<int> BeginFrameNum
		{
			get
			{
				return this._BeginFrameNum;
			}
			set
			{
				if ((this._BeginFrameNum != value))
				{
					this._BeginFrameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PacketTime
		{
			get
			{
				return this._PacketTime;
			}
			set
			{
				if ((this._PacketTime != value))
				{
					this._PacketTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PacketTime(ms)]", Storage="_PacketTime_ms_", DbType="Int")]
		public System.Nullable<int> PacketTime_ms_
		{
			get
			{
				return this._PacketTime_ms_;
			}
			set
			{
				if ((this._PacketTime_ms_ != value))
				{
					this._PacketTime_ms_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DumpFor", DbType="NVarChar(30)")]
		public string DumpFor
		{
			get
			{
				return this._DumpFor;
			}
			set
			{
				if ((this._DumpFor != value))
				{
					this._DumpFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handover_Command", DbType="Int")]
		public System.Nullable<int> Handover_Command
		{
			get
			{
				return this._Handover_Command;
			}
			set
			{
				if ((this._Handover_Command != value))
				{
					this._Handover_Command = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handover_Command_time", DbType="NVarChar(200)")]
		public string Handover_Command_time
		{
			get
			{
				return this._Handover_Command_time;
			}
			set
			{
				if ((this._Handover_Command_time != value))
				{
					this._Handover_Command_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handover_Command_MsgType", DbType="NVarChar(200)")]
		public string Handover_Command_MsgType
		{
			get
			{
				return this._Handover_Command_MsgType;
			}
			set
			{
				if ((this._Handover_Command_MsgType != value))
				{
					this._Handover_Command_MsgType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handover_Command_RepeatCounter", DbType="Int")]
		public System.Nullable<int> Handover_Command_RepeatCounter
		{
			get
			{
				return this._Handover_Command_RepeatCounter;
			}
			set
			{
				if ((this._Handover_Command_RepeatCounter != value))
				{
					this._Handover_Command_RepeatCounter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncc", DbType="NVarChar(2)")]
		public string ncc
		{
			get
			{
				return this._ncc;
			}
			set
			{
				if ((this._ncc != value))
				{
					this._ncc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcc", DbType="NVarChar(2)")]
		public string bcc
		{
			get
			{
				return this._bcc;
			}
			set
			{
				if ((this._bcc != value))
				{
					this._bcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch_arfcn", DbType="NVarChar(10)")]
		public string bcch_arfcn
		{
			get
			{
				return this._bcch_arfcn;
			}
			set
			{
				if ((this._bcch_arfcn != value))
				{
					this._bcch_arfcn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chd2_single_ch_ARFCN", DbType="NVarChar(10)")]
		public string chd2_single_ch_ARFCN
		{
			get
			{
				return this._chd2_single_ch_ARFCN;
			}
			set
			{
				if ((this._chd2_single_ch_ARFCN != value))
				{
					this._chd2_single_ch_ARFCN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abis_MR")]
	public partial class Abis_MR
	{
		
		private System.Nullable<int> _FileNum;
		
		private System.Nullable<int> _PacketNum;
		
		private System.Nullable<int> _BeginFrameNum;
		
		private System.Nullable<System.DateTime> _PacketTime;
		
		private System.Nullable<int> _PacketTime_ms_;
		
		private string _DumpFor;
		
		private System.Nullable<int> _Measurement_Report;
		
		private string _Measurement_Report_time;
		
		private string _cell;
		
		private string _bs_power;
		
		private string _ms_power;
		
		private System.Nullable<int> _act_ta;
		
		private string _dtx_used;
		
		private System.Nullable<int> _rxlev_full_serv_cell;
		
		private System.Nullable<int> _rxlev_sub_serv_cell;
		
		private System.Nullable<int> _bsic0;
		
		private System.Nullable<int> _bsic1;
		
		private System.Nullable<int> _bsic2;
		
		private System.Nullable<int> _bsic3;
		
		private System.Nullable<int> _bsic4;
		
		private System.Nullable<int> _bsic5;
		
		private System.Nullable<int> _bcch0;
		
		private System.Nullable<int> _bcch1;
		
		private System.Nullable<int> _bcch2;
		
		private System.Nullable<int> _bcch3;
		
		private System.Nullable<int> _bcch4;
		
		private System.Nullable<int> _bcch5;
		
		private System.Nullable<int> _rxlev0;
		
		private System.Nullable<int> _rxlev1;
		
		private System.Nullable<int> _rxlev2;
		
		private System.Nullable<int> _rxlev3;
		
		private System.Nullable<int> _rxlev4;
		
		private System.Nullable<int> _rxlev5;
		
		public Abis_MR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNum", DbType="Int")]
		public System.Nullable<int> FileNum
		{
			get
			{
				return this._FileNum;
			}
			set
			{
				if ((this._FileNum != value))
				{
					this._FileNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketNum", DbType="Int")]
		public System.Nullable<int> PacketNum
		{
			get
			{
				return this._PacketNum;
			}
			set
			{
				if ((this._PacketNum != value))
				{
					this._PacketNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginFrameNum", DbType="Int")]
		public System.Nullable<int> BeginFrameNum
		{
			get
			{
				return this._BeginFrameNum;
			}
			set
			{
				if ((this._BeginFrameNum != value))
				{
					this._BeginFrameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PacketTime
		{
			get
			{
				return this._PacketTime;
			}
			set
			{
				if ((this._PacketTime != value))
				{
					this._PacketTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PacketTime(ms)]", Storage="_PacketTime_ms_", DbType="Int")]
		public System.Nullable<int> PacketTime_ms_
		{
			get
			{
				return this._PacketTime_ms_;
			}
			set
			{
				if ((this._PacketTime_ms_ != value))
				{
					this._PacketTime_ms_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DumpFor", DbType="NVarChar(30)")]
		public string DumpFor
		{
			get
			{
				return this._DumpFor;
			}
			set
			{
				if ((this._DumpFor != value))
				{
					this._DumpFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measurement_Report", DbType="Int")]
		public System.Nullable<int> Measurement_Report
		{
			get
			{
				return this._Measurement_Report;
			}
			set
			{
				if ((this._Measurement_Report != value))
				{
					this._Measurement_Report = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measurement_Report_time", DbType="NVarChar(200)")]
		public string Measurement_Report_time
		{
			get
			{
				return this._Measurement_Report_time;
			}
			set
			{
				if ((this._Measurement_Report_time != value))
				{
					this._Measurement_Report_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="NVarChar(200)")]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this._cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bs_power", DbType="NVarChar(200)")]
		public string bs_power
		{
			get
			{
				return this._bs_power;
			}
			set
			{
				if ((this._bs_power != value))
				{
					this._bs_power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_power", DbType="NVarChar(200)")]
		public string ms_power
		{
			get
			{
				return this._ms_power;
			}
			set
			{
				if ((this._ms_power != value))
				{
					this._ms_power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_act_ta", DbType="Int")]
		public System.Nullable<int> act_ta
		{
			get
			{
				return this._act_ta;
			}
			set
			{
				if ((this._act_ta != value))
				{
					this._act_ta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtx_used", DbType="NVarChar(200)")]
		public string dtx_used
		{
			get
			{
				return this._dtx_used;
			}
			set
			{
				if ((this._dtx_used != value))
				{
					this._dtx_used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev_full_serv_cell", DbType="Int")]
		public System.Nullable<int> rxlev_full_serv_cell
		{
			get
			{
				return this._rxlev_full_serv_cell;
			}
			set
			{
				if ((this._rxlev_full_serv_cell != value))
				{
					this._rxlev_full_serv_cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev_sub_serv_cell", DbType="Int")]
		public System.Nullable<int> rxlev_sub_serv_cell
		{
			get
			{
				return this._rxlev_sub_serv_cell;
			}
			set
			{
				if ((this._rxlev_sub_serv_cell != value))
				{
					this._rxlev_sub_serv_cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic0", DbType="Int")]
		public System.Nullable<int> bsic0
		{
			get
			{
				return this._bsic0;
			}
			set
			{
				if ((this._bsic0 != value))
				{
					this._bsic0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic1", DbType="Int")]
		public System.Nullable<int> bsic1
		{
			get
			{
				return this._bsic1;
			}
			set
			{
				if ((this._bsic1 != value))
				{
					this._bsic1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic2", DbType="Int")]
		public System.Nullable<int> bsic2
		{
			get
			{
				return this._bsic2;
			}
			set
			{
				if ((this._bsic2 != value))
				{
					this._bsic2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic3", DbType="Int")]
		public System.Nullable<int> bsic3
		{
			get
			{
				return this._bsic3;
			}
			set
			{
				if ((this._bsic3 != value))
				{
					this._bsic3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic4", DbType="Int")]
		public System.Nullable<int> bsic4
		{
			get
			{
				return this._bsic4;
			}
			set
			{
				if ((this._bsic4 != value))
				{
					this._bsic4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic5", DbType="Int")]
		public System.Nullable<int> bsic5
		{
			get
			{
				return this._bsic5;
			}
			set
			{
				if ((this._bsic5 != value))
				{
					this._bsic5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch0", DbType="Int")]
		public System.Nullable<int> bcch0
		{
			get
			{
				return this._bcch0;
			}
			set
			{
				if ((this._bcch0 != value))
				{
					this._bcch0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch1", DbType="Int")]
		public System.Nullable<int> bcch1
		{
			get
			{
				return this._bcch1;
			}
			set
			{
				if ((this._bcch1 != value))
				{
					this._bcch1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch2", DbType="Int")]
		public System.Nullable<int> bcch2
		{
			get
			{
				return this._bcch2;
			}
			set
			{
				if ((this._bcch2 != value))
				{
					this._bcch2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch3", DbType="Int")]
		public System.Nullable<int> bcch3
		{
			get
			{
				return this._bcch3;
			}
			set
			{
				if ((this._bcch3 != value))
				{
					this._bcch3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch4", DbType="Int")]
		public System.Nullable<int> bcch4
		{
			get
			{
				return this._bcch4;
			}
			set
			{
				if ((this._bcch4 != value))
				{
					this._bcch4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch5", DbType="Int")]
		public System.Nullable<int> bcch5
		{
			get
			{
				return this._bcch5;
			}
			set
			{
				if ((this._bcch5 != value))
				{
					this._bcch5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev0", DbType="Int")]
		public System.Nullable<int> rxlev0
		{
			get
			{
				return this._rxlev0;
			}
			set
			{
				if ((this._rxlev0 != value))
				{
					this._rxlev0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev1", DbType="Int")]
		public System.Nullable<int> rxlev1
		{
			get
			{
				return this._rxlev1;
			}
			set
			{
				if ((this._rxlev1 != value))
				{
					this._rxlev1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev2", DbType="Int")]
		public System.Nullable<int> rxlev2
		{
			get
			{
				return this._rxlev2;
			}
			set
			{
				if ((this._rxlev2 != value))
				{
					this._rxlev2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev3", DbType="Int")]
		public System.Nullable<int> rxlev3
		{
			get
			{
				return this._rxlev3;
			}
			set
			{
				if ((this._rxlev3 != value))
				{
					this._rxlev3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev4", DbType="Int")]
		public System.Nullable<int> rxlev4
		{
			get
			{
				return this._rxlev4;
			}
			set
			{
				if ((this._rxlev4 != value))
				{
					this._rxlev4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev5", DbType="Int")]
		public System.Nullable<int> rxlev5
		{
			get
			{
				return this._rxlev5;
			}
			set
			{
				if ((this._rxlev5 != value))
				{
					this._rxlev5 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
