#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq2SqlGeography.LinqSql.FromOSS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SqlSpatialJiangmeng")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMCOMNEIGH(MCOMNEIGH instance);
    partial void UpdateMCOMNEIGH(MCOMNEIGH instance);
    partial void DeleteMCOMNEIGH(MCOMNEIGH instance);
    partial void InsertMCOMCARRIER(MCOMCARRIER instance);
    partial void UpdateMCOMCARRIER(MCOMCARRIER instance);
    partial void DeleteMCOMCARRIER(MCOMCARRIER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Linq2SqlGeography.Properties.Settings.Default.SqlSpatialTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MCOMNEIGH> MCOMNEIGH
		{
			get
			{
				return this.GetTable<MCOMNEIGH>();
			}
		}
		
		public System.Data.Linq.Table<MCOMCARRIER> MCOMCARRIER
		{
			get
			{
				return this.GetTable<MCOMCARRIER>();
			}
		}
		
		public System.Data.Linq.Table<SITE> SITE
		{
			get
			{
				return this.GetTable<SITE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MCOMNEIGH")]
	public partial class MCOMNEIGH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cell;
		
		private string _ncell;
		
		private int _MI_PRINX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCellChanging(string value);
    partial void OnCellChanged();
    partial void OnncellChanging(string value);
    partial void OnncellChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    #endregion
		
		public MCOMNEIGH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(10)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this.OnCellChanging(value);
					this.SendPropertyChanging();
					this._Cell = value;
					this.SendPropertyChanged("Cell");
					this.OnCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncell", DbType="VarChar(254)")]
		public string ncell
		{
			get
			{
				return this._ncell;
			}
			set
			{
				if ((this._ncell != value))
				{
					this.OnncellChanging(value);
					this.SendPropertyChanging();
					this._ncell = value;
					this.SendPropertyChanged("ncell");
					this.OnncellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MCOMCARRIER")]
	public partial class MCOMCARRIER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cell;
		
		private string _BSC;
		
		private string _LAI;
		
		private string _CI;
		
		private string _BCCH;
		
		private string _BSIC;
		
		private string _TCH;
		
		private string _HOP;
		
		private string _HSN;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<short> _Dir;
		
		private System.Nullable<short> _Ant_size;
		
		private System.Nullable<short> _Font_size;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCellChanging(string value);
    partial void OnCellChanged();
    partial void OnBSCChanging(string value);
    partial void OnBSCChanged();
    partial void OnLAIChanging(string value);
    partial void OnLAIChanged();
    partial void OnCIChanging(string value);
    partial void OnCIChanged();
    partial void OnBCCHChanging(string value);
    partial void OnBCCHChanged();
    partial void OnBSICChanging(string value);
    partial void OnBSICChanged();
    partial void OnTCHChanging(string value);
    partial void OnTCHChanged();
    partial void OnHOPChanging(string value);
    partial void OnHOPChanged();
    partial void OnHSNChanging(string value);
    partial void OnHSNChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnDirChanging(System.Nullable<short> value);
    partial void OnDirChanged();
    partial void OnAnt_sizeChanging(System.Nullable<short> value);
    partial void OnAnt_sizeChanged();
    partial void OnFont_sizeChanging(System.Nullable<short> value);
    partial void OnFont_sizeChanged();
    partial void OnMI_STYLEChanging(string value);
    partial void OnMI_STYLEChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    partial void OnSP_GEOMETRYChanging(Microsoft.SqlServer.Types.SqlGeometry value);
    partial void OnSP_GEOMETRYChanged();
    #endregion
		
		public MCOMCARRIER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(10)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this.OnCellChanging(value);
					this.SendPropertyChanging();
					this._Cell = value;
					this.SendPropertyChanged("Cell");
					this.OnCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="VarChar(10)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this.OnBSCChanging(value);
					this.SendPropertyChanging();
					this._BSC = value;
					this.SendPropertyChanged("BSC");
					this.OnBSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAI", DbType="VarChar(6)")]
		public string LAI
		{
			get
			{
				return this._LAI;
			}
			set
			{
				if ((this._LAI != value))
				{
					this.OnLAIChanging(value);
					this.SendPropertyChanging();
					this._LAI = value;
					this.SendPropertyChanged("LAI");
					this.OnLAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="VarChar(6)")]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this.OnCIChanging(value);
					this.SendPropertyChanging();
					this._CI = value;
					this.SendPropertyChanged("CI");
					this.OnCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCCH", DbType="VarChar(6)")]
		public string BCCH
		{
			get
			{
				return this._BCCH;
			}
			set
			{
				if ((this._BCCH != value))
				{
					this.OnBCCHChanging(value);
					this.SendPropertyChanging();
					this._BCCH = value;
					this.SendPropertyChanged("BCCH");
					this.OnBCCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSIC", DbType="VarChar(4)")]
		public string BSIC
		{
			get
			{
				return this._BSIC;
			}
			set
			{
				if ((this._BSIC != value))
				{
					this.OnBSICChanging(value);
					this.SendPropertyChanging();
					this._BSIC = value;
					this.SendPropertyChanged("BSIC");
					this.OnBSICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCH", DbType="VarChar(200)")]
		public string TCH
		{
			get
			{
				return this._TCH;
			}
			set
			{
				if ((this._TCH != value))
				{
					this.OnTCHChanging(value);
					this.SendPropertyChanging();
					this._TCH = value;
					this.SendPropertyChanged("TCH");
					this.OnTCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOP", DbType="VarChar(40)")]
		public string HOP
		{
			get
			{
				return this._HOP;
			}
			set
			{
				if ((this._HOP != value))
				{
					this.OnHOPChanging(value);
					this.SendPropertyChanging();
					this._HOP = value;
					this.SendPropertyChanged("HOP");
					this.OnHOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSN", DbType="VarChar(40)")]
		public string HSN
		{
			get
			{
				return this._HSN;
			}
			set
			{
				if ((this._HSN != value))
				{
					this.OnHSNChanging(value);
					this.SendPropertyChanging();
					this._HSN = value;
					this.SendPropertyChanged("HSN");
					this.OnHSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="SmallInt")]
		public System.Nullable<short> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this.OnDirChanging(value);
					this.SendPropertyChanging();
					this._Dir = value;
					this.SendPropertyChanged("Dir");
					this.OnDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ant_size", DbType="SmallInt")]
		public System.Nullable<short> Ant_size
		{
			get
			{
				return this._Ant_size;
			}
			set
			{
				if ((this._Ant_size != value))
				{
					this.OnAnt_sizeChanging(value);
					this.SendPropertyChanging();
					this._Ant_size = value;
					this.SendPropertyChanged("Ant_size");
					this.OnAnt_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Font_size", DbType="SmallInt")]
		public System.Nullable<short> Font_size
		{
			get
			{
				return this._Font_size;
			}
			set
			{
				if ((this._Font_size != value))
				{
					this.OnFont_sizeChanging(value);
					this.SendPropertyChanging();
					this._Font_size = value;
					this.SendPropertyChanged("Font_size");
					this.OnFont_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this.OnMI_STYLEChanging(value);
					this.SendPropertyChanging();
					this._MI_STYLE = value;
					this.SendPropertyChanged("MI_STYLE");
					this.OnMI_STYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this.OnSP_GEOMETRYChanging(value);
					this.SendPropertyChanging();
					this._SP_GEOMETRY = value;
					this.SendPropertyChanged("SP_GEOMETRY");
					this.OnSP_GEOMETRYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SITE")]
	public partial class SITE
	{
		
		private string _msc;
		
		private string _bsc;
		
		private string _cell;
		
		private string _cell_name;
		
		private System.Nullable<decimal> _longitude;
		
		private System.Nullable<decimal> _latitude;
		
		private int _band;
		
		private System.Nullable<decimal> _arfcn;
		
		private string _height;
		
		private System.Nullable<decimal> _dir;
		
		private System.Nullable<decimal> _tilt;
		
		private System.Nullable<int> _ant_bw;
		
		private System.Nullable<int> _power;
		
		private string _ant_gain;
		
		private string _ant_type;
		
		private System.Nullable<int> _ant_size;
		
		public SITE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msc", DbType="NVarChar(30)")]
		public string msc
		{
			get
			{
				return this._msc;
			}
			set
			{
				if ((this._msc != value))
				{
					this._msc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsc", DbType="NVarChar(30)")]
		public string bsc
		{
			get
			{
				return this._bsc;
			}
			set
			{
				if ((this._bsc != value))
				{
					this._bsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="NVarChar(30)")]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this._cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="NVarChar(90)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this._cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(11,6)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(11,6)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_band", DbType="Int NOT NULL")]
		public int band
		{
			get
			{
				return this._band;
			}
			set
			{
				if ((this._band != value))
				{
					this._band = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arfcn", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> arfcn
		{
			get
			{
				return this._arfcn;
			}
			set
			{
				if ((this._arfcn != value))
				{
					this._arfcn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="VarChar(3)")]
		public string height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this._height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> dir
		{
			get
			{
				return this._dir;
			}
			set
			{
				if ((this._dir != value))
				{
					this._dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilt", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> tilt
		{
			get
			{
				return this._tilt;
			}
			set
			{
				if ((this._tilt != value))
				{
					this._tilt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_bw", DbType="Int")]
		public System.Nullable<int> ant_bw
		{
			get
			{
				return this._ant_bw;
			}
			set
			{
				if ((this._ant_bw != value))
				{
					this._ant_bw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="Int")]
		public System.Nullable<int> power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this._power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_gain", DbType="VarChar(3)")]
		public string ant_gain
		{
			get
			{
				return this._ant_gain;
			}
			set
			{
				if ((this._ant_gain != value))
				{
					this._ant_gain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_type", DbType="VarChar(15)")]
		public string ant_type
		{
			get
			{
				return this._ant_type;
			}
			set
			{
				if ((this._ant_type != value))
				{
					this._ant_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_size", DbType="Int")]
		public System.Nullable<int> ant_size
		{
			get
			{
				return this._ant_size;
			}
			set
			{
				if ((this._ant_size != value))
				{
					this._ant_size = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
