#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq2SqlGeography.LinqSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SqlSpatialJiangmeng")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert城市内部主要交通干道(城市内部主要交通干道 instance);
    partial void Update城市内部主要交通干道(城市内部主要交通干道 instance);
    partial void Delete城市内部主要交通干道(城市内部主要交通干道 instance);
    partial void InsertMCOMNEIGH(MCOMNEIGH instance);
    partial void UpdateMCOMNEIGH(MCOMNEIGH instance);
    partial void DeleteMCOMNEIGH(MCOMNEIGH instance);
    partial void InsertMCOMCARRIER(MCOMCARRIER instance);
    partial void UpdateMCOMCARRIER(MCOMCARRIER instance);
    partial void DeleteMCOMCARRIER(MCOMCARRIER instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::Linq2SqlGeography.Properties.Settings.Default.SqlSpatialTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CellTracing> CellTracing
		{
			get
			{
				return this.GetTable<CellTracing>();
			}
		}
		
		public System.Data.Linq.Table<SITE> SITE
		{
			get
			{
				return this.GetTable<SITE>();
			}
		}
		
		public System.Data.Linq.Table<EventLocating> EventLocating
		{
			get
			{
				return this.GetTable<EventLocating>();
			}
		}
		
		public System.Data.Linq.Table<城市内部主要交通干道> 城市内部主要交通干道
		{
			get
			{
				return this.GetTable<城市内部主要交通干道>();
			}
		}
		
		public System.Data.Linq.Table<MCOMNEIGH> MCOMNEIGH
		{
			get
			{
				return this.GetTable<MCOMNEIGH>();
			}
		}
		
		public System.Data.Linq.Table<MCOMCARRIER> MCOMCARRIER
		{
			get
			{
				return this.GetTable<MCOMCARRIER>();
			}
		}
		
		public System.Data.Linq.Table<Abis_MR> Abis_MR
		{
			get
			{
				return this.GetTable<Abis_MR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CellTracing")]
	public partial class CellTracing
	{
		
		private string _SiteName;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
		public CellTracing()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(30)")]
		public string cell
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this._MI_STYLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this._MI_PRINX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this._SP_GEOMETRY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SITE")]
	public partial class SITE
	{
		
		private string _msc;
		
		private string _bsc;
		
		private string _cell;
		
		private string _cell_name;
		
		private System.Nullable<decimal> _longitude;
		
		private System.Nullable<decimal> _latitude;
		
		private int _band;
		
		private System.Nullable<decimal> _arfcn;
		
		private string _height;
		
		private System.Nullable<decimal> _dir;
		
		private System.Nullable<decimal> _tilt;
		
		private System.Nullable<int> _ant_bw;
		
		private System.Nullable<int> _power;
		
		private string _ant_gain;
		
		private string _ant_type;
		
		private System.Nullable<int> _ant_size;
		
		public SITE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msc", DbType="NVarChar(30)")]
		public string msc
		{
			get
			{
				return this._msc;
			}
			set
			{
				if ((this._msc != value))
				{
					this._msc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsc", DbType="NVarChar(30)")]
		public string bsc
		{
			get
			{
				return this._bsc;
			}
			set
			{
				if ((this._bsc != value))
				{
					this._bsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="NVarChar(30)")]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this._cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="VarChar(21)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this._cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(11,6)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(11,6)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_band", DbType="Int NOT NULL")]
		public int band
		{
			get
			{
				return this._band;
			}
			set
			{
				if ((this._band != value))
				{
					this._band = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arfcn", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> arfcn
		{
			get
			{
				return this._arfcn;
			}
			set
			{
				if ((this._arfcn != value))
				{
					this._arfcn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="VarChar(3)")]
		public string height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this._height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> dir
		{
			get
			{
				return this._dir;
			}
			set
			{
				if ((this._dir != value))
				{
					this._dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilt", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> tilt
		{
			get
			{
				return this._tilt;
			}
			set
			{
				if ((this._tilt != value))
				{
					this._tilt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_bw", DbType="Int")]
		public System.Nullable<int> ant_bw
		{
			get
			{
				return this._ant_bw;
			}
			set
			{
				if ((this._ant_bw != value))
				{
					this._ant_bw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="Int")]
		public System.Nullable<int> power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this._power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_gain", DbType="VarChar(3)")]
		public string ant_gain
		{
			get
			{
				return this._ant_gain;
			}
			set
			{
				if ((this._ant_gain != value))
				{
					this._ant_gain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_type", DbType="VarChar(15)")]
		public string ant_type
		{
			get
			{
				return this._ant_type;
			}
			set
			{
				if ((this._ant_type != value))
				{
					this._ant_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ant_size", DbType="Int")]
		public System.Nullable<int> ant_size
		{
			get
			{
				return this._ant_size;
			}
			set
			{
				if ((this._ant_size != value))
				{
					this._ant_size = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventLocating")]
	public partial class EventLocating
	{
		
		private string _SiteName;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
		public EventLocating()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(30)")]
		public string events
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this._MI_STYLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this._MI_PRINX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this._SP_GEOMETRY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.城市内部主要交通干道")]
	public partial class 城市内部主要交通干道 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _编码;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On编码Changing(string value);
    partial void On编码Changed();
    partial void OnMI_STYLEChanging(string value);
    partial void OnMI_STYLEChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    partial void OnSP_GEOMETRYChanging(Microsoft.SqlServer.Types.SqlGeometry value);
    partial void OnSP_GEOMETRYChanged();
    #endregion
		
		public 城市内部主要交通干道()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_编码", DbType="VarChar(4)")]
		public string 编码
		{
			get
			{
				return this._编码;
			}
			set
			{
				if ((this._编码 != value))
				{
					this.On编码Changing(value);
					this.SendPropertyChanging();
					this._编码 = value;
					this.SendPropertyChanged("编码");
					this.On编码Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this.OnMI_STYLEChanging(value);
					this.SendPropertyChanging();
					this._MI_STYLE = value;
					this.SendPropertyChanged("MI_STYLE");
					this.OnMI_STYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this.OnSP_GEOMETRYChanging(value);
					this.SendPropertyChanging();
					this._SP_GEOMETRY = value;
					this.SendPropertyChanged("SP_GEOMETRY");
					this.OnSP_GEOMETRYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MCOMNEIGH")]
	public partial class MCOMNEIGH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cell;
		
		private string _ncell;
		
		private int _MI_PRINX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCellChanging(string value);
    partial void OnCellChanged();
    partial void OnncellChanging(string value);
    partial void OnncellChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    #endregion
		
		public MCOMNEIGH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(10)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this.OnCellChanging(value);
					this.SendPropertyChanging();
					this._Cell = value;
					this.SendPropertyChanged("Cell");
					this.OnCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncell", DbType="VarChar(254)")]
		public string ncell
		{
			get
			{
				return this._ncell;
			}
			set
			{
				if ((this._ncell != value))
				{
					this.OnncellChanging(value);
					this.SendPropertyChanging();
					this._ncell = value;
					this.SendPropertyChanged("ncell");
					this.OnncellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MCOMCARRIER")]
	public partial class MCOMCARRIER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cell;
		
		private string _BSC;
		
		private string _LAI;
		
		private string _CI;
		
		private System.Nullable<short> _BCCH;
		
		private string _BSIC;
		
		private string _TCH;
		
		private string _HOP;
		
		private string _HSN;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<short> _Dir;
		
		private System.Nullable<short> _Ant_size;
		
		private System.Nullable<short> _Font_size;
		
		private string _MI_STYLE;
		
		private int _MI_PRINX;
		
		private Microsoft.SqlServer.Types.SqlGeometry _SP_GEOMETRY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCellChanging(string value);
    partial void OnCellChanged();
    partial void OnBSCChanging(string value);
    partial void OnBSCChanged();
    partial void OnLAIChanging(string value);
    partial void OnLAIChanged();
    partial void OnCIChanging(string value);
    partial void OnCIChanged();
    partial void OnBCCHChanging(System.Nullable<short> value);
    partial void OnBCCHChanged();
    partial void OnBSICChanging(string value);
    partial void OnBSICChanged();
    partial void OnTCHChanging(string value);
    partial void OnTCHChanged();
    partial void OnHOPChanging(string value);
    partial void OnHOPChanged();
    partial void OnHSNChanging(string value);
    partial void OnHSNChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnDirChanging(System.Nullable<short> value);
    partial void OnDirChanged();
    partial void OnAnt_sizeChanging(System.Nullable<short> value);
    partial void OnAnt_sizeChanged();
    partial void OnFont_sizeChanging(System.Nullable<short> value);
    partial void OnFont_sizeChanged();
    partial void OnMI_STYLEChanging(string value);
    partial void OnMI_STYLEChanged();
    partial void OnMI_PRINXChanging(int value);
    partial void OnMI_PRINXChanged();
    partial void OnSP_GEOMETRYChanging(Microsoft.SqlServer.Types.SqlGeometry value);
    partial void OnSP_GEOMETRYChanged();
    #endregion
		
		public MCOMCARRIER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(10)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this.OnCellChanging(value);
					this.SendPropertyChanging();
					this._Cell = value;
					this.SendPropertyChanged("Cell");
					this.OnCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="VarChar(10)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this.OnBSCChanging(value);
					this.SendPropertyChanging();
					this._BSC = value;
					this.SendPropertyChanged("BSC");
					this.OnBSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAI", DbType="VarChar(6)")]
		public string LAI
		{
			get
			{
				return this._LAI;
			}
			set
			{
				if ((this._LAI != value))
				{
					this.OnLAIChanging(value);
					this.SendPropertyChanging();
					this._LAI = value;
					this.SendPropertyChanged("LAI");
					this.OnLAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="VarChar(6)")]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this.OnCIChanging(value);
					this.SendPropertyChanging();
					this._CI = value;
					this.SendPropertyChanged("CI");
					this.OnCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCCH", DbType="SmallInt")]
		public System.Nullable<short> BCCH
		{
			get
			{
				return this._BCCH;
			}
			set
			{
				if ((this._BCCH != value))
				{
					this.OnBCCHChanging(value);
					this.SendPropertyChanging();
					this._BCCH = value;
					this.SendPropertyChanged("BCCH");
					this.OnBCCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSIC", DbType="VarChar(4)")]
		public string BSIC
		{
			get
			{
				return this._BSIC;
			}
			set
			{
				if ((this._BSIC != value))
				{
					this.OnBSICChanging(value);
					this.SendPropertyChanging();
					this._BSIC = value;
					this.SendPropertyChanged("BSIC");
					this.OnBSICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCH", DbType="VarChar(200)")]
		public string TCH
		{
			get
			{
				return this._TCH;
			}
			set
			{
				if ((this._TCH != value))
				{
					this.OnTCHChanging(value);
					this.SendPropertyChanging();
					this._TCH = value;
					this.SendPropertyChanged("TCH");
					this.OnTCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOP", DbType="VarChar(40)")]
		public string HOP
		{
			get
			{
				return this._HOP;
			}
			set
			{
				if ((this._HOP != value))
				{
					this.OnHOPChanging(value);
					this.SendPropertyChanging();
					this._HOP = value;
					this.SendPropertyChanged("HOP");
					this.OnHOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSN", DbType="VarChar(40)")]
		public string HSN
		{
			get
			{
				return this._HSN;
			}
			set
			{
				if ((this._HSN != value))
				{
					this.OnHSNChanging(value);
					this.SendPropertyChanging();
					this._HSN = value;
					this.SendPropertyChanged("HSN");
					this.OnHSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="SmallInt")]
		public System.Nullable<short> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this.OnDirChanging(value);
					this.SendPropertyChanging();
					this._Dir = value;
					this.SendPropertyChanged("Dir");
					this.OnDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ant_size", DbType="SmallInt")]
		public System.Nullable<short> Ant_size
		{
			get
			{
				return this._Ant_size;
			}
			set
			{
				if ((this._Ant_size != value))
				{
					this.OnAnt_sizeChanging(value);
					this.SendPropertyChanging();
					this._Ant_size = value;
					this.SendPropertyChanged("Ant_size");
					this.OnAnt_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Font_size", DbType="SmallInt")]
		public System.Nullable<short> Font_size
		{
			get
			{
				return this._Font_size;
			}
			set
			{
				if ((this._Font_size != value))
				{
					this.OnFont_sizeChanging(value);
					this.SendPropertyChanging();
					this._Font_size = value;
					this.SendPropertyChanged("Font_size");
					this.OnFont_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_STYLE", DbType="VarChar(254)")]
		public string MI_STYLE
		{
			get
			{
				return this._MI_STYLE;
			}
			set
			{
				if ((this._MI_STYLE != value))
				{
					this.OnMI_STYLEChanging(value);
					this.SendPropertyChanging();
					this._MI_STYLE = value;
					this.SendPropertyChanged("MI_STYLE");
					this.OnMI_STYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI_PRINX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MI_PRINX
		{
			get
			{
				return this._MI_PRINX;
			}
			set
			{
				if ((this._MI_PRINX != value))
				{
					this.OnMI_PRINXChanging(value);
					this.SendPropertyChanging();
					this._MI_PRINX = value;
					this.SendPropertyChanged("MI_PRINX");
					this.OnMI_PRINXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_GEOMETRY", UpdateCheck=UpdateCheck.Never)]
		public Microsoft.SqlServer.Types.SqlGeometry SP_GEOMETRY
		{
			get
			{
				return this._SP_GEOMETRY;
			}
			set
			{
				if ((this._SP_GEOMETRY != value))
				{
					this.OnSP_GEOMETRYChanging(value);
					this.SendPropertyChanging();
					this._SP_GEOMETRY = value;
					this.SendPropertyChanged("SP_GEOMETRY");
					this.OnSP_GEOMETRYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abis_MR")]
	public partial class Abis_MR
	{
		
		private System.Nullable<int> _FileNum;
		
		private System.Nullable<int> _PacketNum;
		
		private System.Nullable<int> _BeginFrameNum;
		
		private System.Nullable<System.DateTime> _PacketTime;
		
		private System.Nullable<int> _PacketTime_ms_;
		
		private string _DumpFor;
		
		private System.Nullable<int> _Measurement_Report;
		
		private string _Measurement_Report_time;
		
		private string _cell;
		
		private string _bs_power;
		
		private string _ms_power;
		
		private System.Nullable<int> _act_ta;
		
		private string _dtx_used;
		
		private System.Nullable<int> _rxlev_full_serv_cell;
		
		private System.Nullable<int> _rxlev_sub_serv_cell;
		
		private System.Nullable<int> _bsic0;
		
		private System.Nullable<int> _bsic1;
		
		private System.Nullable<int> _bsic2;
		
		private System.Nullable<int> _bsic3;
		
		private System.Nullable<int> _bsic4;
		
		private System.Nullable<int> _bsic5;
		
		private System.Nullable<int> _bcch0;
		
		private System.Nullable<int> _bcch1;
		
		private System.Nullable<int> _bcch2;
		
		private System.Nullable<int> _bcch3;
		
		private System.Nullable<int> _bcch4;
		
		private System.Nullable<int> _bcch5;
		
		private System.Nullable<int> _rxlev0;
		
		private System.Nullable<int> _rxlev1;
		
		private System.Nullable<int> _rxlev2;
		
		private System.Nullable<int> _rxlev3;
		
		private System.Nullable<int> _rxlev4;
		
		private System.Nullable<int> _rxlev5;
		
		public Abis_MR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNum", DbType="Int")]
		public System.Nullable<int> FileNum
		{
			get
			{
				return this._FileNum;
			}
			set
			{
				if ((this._FileNum != value))
				{
					this._FileNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketNum", DbType="Int")]
		public System.Nullable<int> PacketNum
		{
			get
			{
				return this._PacketNum;
			}
			set
			{
				if ((this._PacketNum != value))
				{
					this._PacketNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginFrameNum", DbType="Int")]
		public System.Nullable<int> BeginFrameNum
		{
			get
			{
				return this._BeginFrameNum;
			}
			set
			{
				if ((this._BeginFrameNum != value))
				{
					this._BeginFrameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PacketTime
		{
			get
			{
				return this._PacketTime;
			}
			set
			{
				if ((this._PacketTime != value))
				{
					this._PacketTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PacketTime(ms)]", Storage="_PacketTime_ms_", DbType="Int")]
		public System.Nullable<int> PacketTime_ms_
		{
			get
			{
				return this._PacketTime_ms_;
			}
			set
			{
				if ((this._PacketTime_ms_ != value))
				{
					this._PacketTime_ms_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DumpFor", DbType="NVarChar(30)")]
		public string DumpFor
		{
			get
			{
				return this._DumpFor;
			}
			set
			{
				if ((this._DumpFor != value))
				{
					this._DumpFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measurement_Report", DbType="Int")]
		public System.Nullable<int> Measurement_Report
		{
			get
			{
				return this._Measurement_Report;
			}
			set
			{
				if ((this._Measurement_Report != value))
				{
					this._Measurement_Report = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measurement_Report_time", DbType="NVarChar(200)")]
		public string Measurement_Report_time
		{
			get
			{
				return this._Measurement_Report_time;
			}
			set
			{
				if ((this._Measurement_Report_time != value))
				{
					this._Measurement_Report_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="NVarChar(200)")]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this._cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bs_power", DbType="NVarChar(200)")]
		public string bs_power
		{
			get
			{
				return this._bs_power;
			}
			set
			{
				if ((this._bs_power != value))
				{
					this._bs_power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_power", DbType="NVarChar(200)")]
		public string ms_power
		{
			get
			{
				return this._ms_power;
			}
			set
			{
				if ((this._ms_power != value))
				{
					this._ms_power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_act_ta", DbType="Int")]
		public System.Nullable<int> act_ta
		{
			get
			{
				return this._act_ta;
			}
			set
			{
				if ((this._act_ta != value))
				{
					this._act_ta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtx_used", DbType="NVarChar(200)")]
		public string dtx_used
		{
			get
			{
				return this._dtx_used;
			}
			set
			{
				if ((this._dtx_used != value))
				{
					this._dtx_used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev_full_serv_cell", DbType="Int")]
		public System.Nullable<int> rxlev_full_serv_cell
		{
			get
			{
				return this._rxlev_full_serv_cell;
			}
			set
			{
				if ((this._rxlev_full_serv_cell != value))
				{
					this._rxlev_full_serv_cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev_sub_serv_cell", DbType="Int")]
		public System.Nullable<int> rxlev_sub_serv_cell
		{
			get
			{
				return this._rxlev_sub_serv_cell;
			}
			set
			{
				if ((this._rxlev_sub_serv_cell != value))
				{
					this._rxlev_sub_serv_cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic0", DbType="Int")]
		public System.Nullable<int> bsic0
		{
			get
			{
				return this._bsic0;
			}
			set
			{
				if ((this._bsic0 != value))
				{
					this._bsic0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic1", DbType="Int")]
		public System.Nullable<int> bsic1
		{
			get
			{
				return this._bsic1;
			}
			set
			{
				if ((this._bsic1 != value))
				{
					this._bsic1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic2", DbType="Int")]
		public System.Nullable<int> bsic2
		{
			get
			{
				return this._bsic2;
			}
			set
			{
				if ((this._bsic2 != value))
				{
					this._bsic2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic3", DbType="Int")]
		public System.Nullable<int> bsic3
		{
			get
			{
				return this._bsic3;
			}
			set
			{
				if ((this._bsic3 != value))
				{
					this._bsic3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic4", DbType="Int")]
		public System.Nullable<int> bsic4
		{
			get
			{
				return this._bsic4;
			}
			set
			{
				if ((this._bsic4 != value))
				{
					this._bsic4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsic5", DbType="Int")]
		public System.Nullable<int> bsic5
		{
			get
			{
				return this._bsic5;
			}
			set
			{
				if ((this._bsic5 != value))
				{
					this._bsic5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch0", DbType="Int")]
		public System.Nullable<int> bcch0
		{
			get
			{
				return this._bcch0;
			}
			set
			{
				if ((this._bcch0 != value))
				{
					this._bcch0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch1", DbType="Int")]
		public System.Nullable<int> bcch1
		{
			get
			{
				return this._bcch1;
			}
			set
			{
				if ((this._bcch1 != value))
				{
					this._bcch1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch2", DbType="Int")]
		public System.Nullable<int> bcch2
		{
			get
			{
				return this._bcch2;
			}
			set
			{
				if ((this._bcch2 != value))
				{
					this._bcch2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch3", DbType="Int")]
		public System.Nullable<int> bcch3
		{
			get
			{
				return this._bcch3;
			}
			set
			{
				if ((this._bcch3 != value))
				{
					this._bcch3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch4", DbType="Int")]
		public System.Nullable<int> bcch4
		{
			get
			{
				return this._bcch4;
			}
			set
			{
				if ((this._bcch4 != value))
				{
					this._bcch4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcch5", DbType="Int")]
		public System.Nullable<int> bcch5
		{
			get
			{
				return this._bcch5;
			}
			set
			{
				if ((this._bcch5 != value))
				{
					this._bcch5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev0", DbType="Int")]
		public System.Nullable<int> rxlev0
		{
			get
			{
				return this._rxlev0;
			}
			set
			{
				if ((this._rxlev0 != value))
				{
					this._rxlev0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev1", DbType="Int")]
		public System.Nullable<int> rxlev1
		{
			get
			{
				return this._rxlev1;
			}
			set
			{
				if ((this._rxlev1 != value))
				{
					this._rxlev1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev2", DbType="Int")]
		public System.Nullable<int> rxlev2
		{
			get
			{
				return this._rxlev2;
			}
			set
			{
				if ((this._rxlev2 != value))
				{
					this._rxlev2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev3", DbType="Int")]
		public System.Nullable<int> rxlev3
		{
			get
			{
				return this._rxlev3;
			}
			set
			{
				if ((this._rxlev3 != value))
				{
					this._rxlev3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev4", DbType="Int")]
		public System.Nullable<int> rxlev4
		{
			get
			{
				return this._rxlev4;
			}
			set
			{
				if ((this._rxlev4 != value))
				{
					this._rxlev4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rxlev5", DbType="Int")]
		public System.Nullable<int> rxlev5
		{
			get
			{
				return this._rxlev5;
			}
			set
			{
				if ((this._rxlev5 != value))
				{
					this._rxlev5 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
